sidorares/node-mysql2

benchmarks/unit/packet_parser.js
lib/commands/execute.js
lib/connection.js
lib/packet_parser.js
lib/packets/binlog_dump.js
lib/packets/column_definition.js
lib/packets/execute.js
lib/packets/handshake.js
lib/packets/handshake_response.js
lib/packets/index.js
lib/packets/packet.js
lib/packets/prepare_statement.js
lib/packets/query.js
lib/packets/register_slave.js
lib/packets/resultset_header.js
lib/packets/ssl_request.js
lib/packets/text_row.js
package.json
test/unit/test-packet-parser.js

add tests and benchmark,
100% speed improvement (packet_parser only, not integral)

refactor packet_parser

---

lib/commands/index.js
lib/commands/quit.js
lib/commands/server_handshake.js
lib/connection.js
lib/server.js
test/common.js
test/integration/connection/test-disconnects.js
test/integration/connection/test-quit.js

see #135 
might be related to #162

Send com_quit command as result of connection.end()

---

lib/pool.js

WIP
needs benchmarks and pool integration tests

use deque instead of arrays for pool queues

---

.travis.yml
test/integration/connection/test-execute-nocolumndef.js

mariadb/mysql return fields in different order

travis: add mariadb to tests. 

---

lib/pool.js

This pr is just one of the method to fix #226.
If this library has similarity with node-mysql, `connection._pool = null;` at https://github.com/felixge/node-mysql/blob/master/lib/Pool.js#L261 might be necessary.

Add spliceConnection function

---

lib/compile_binary_parser.js
lib/compile_text_parser.js
lib/constants/types.js

WIP
need to figure out how to add mysql 5.7 to CI matrix ( or at least add tests that are skipped if version < 5.7 )

add json type support (mysql 5.7) #207

---

lib/packets/packet.js
test/integration/connection/test-datetime.js

return null date as null, not INVALID_DATE. closes #244

---

README.md
lib/compile_binary_parser.js
lib/compile_text_parser.js
lib/connection_config.js
test/common.js
test/integration/connection/test-decimals-as-numbers.js

I know you say it is faster to have decimals as strings but we really need to have an override to make them numbers. I went ahead and added the option. Would you be game to merge this into master or another branch? It was a simple add and I also included some tests for it.

Add decimal numbers option

---

lib/packets/packet.js
test/integration/connection/test-timestamp.js
test/unit/packets/test-datetime.js

fix 11 byte binary timestamp deserialisation

---

.gitignore
README.md
examples/mysqlproxy.js
lib/commands/server_handshake.js
lib/connection.js
lib/constants/client.js
lib/packets/column_definition.js
lib/packets/packet.js
test/unit/packets/test-column-definition.js

Also:
- Made a server pattern of: emit event if there are listeners, or fallback to default
- Added some docs
- Updated CLIENT constants and made them hex for readability

emit packet event

---

lib/compile_text_parser.js
test/common.js
test/integration/connection/test-typecast-global-option.js

enabled use of global typeCast

---

test/common.js
test/run.js

set TZ=0 so test works everywhere

---

Contributing.md
License
README.md

Docs update

---

lib/packets/packet.js
lib/packets/resultset_header.js
package.json
test/integration/connection/test-insert-bigint.js
test/integration/connection/test-insert-negative-ai.js

Changes
- Fixed the wrong use of unsigned flag
- Improved test for negative autoincrement test
- Return string when number is too big for JS
Closes #341 Fixes #336 
Thanks @sheeley for initial work

Bn.js to Long

---

test/integration/regressions/test-#82.js

Just a proof of concept that #82 was an userland problem, we can keep the test if we want to prevent future regressions

added test for #82

---

lib/packets/resultset_header.js
test/integration/connection/test-update-changed-rows.js

feat: issue#288

---

lib/connection.js
test/common.js
test/integration/config/test-connect-timeout.js

Closes https://github.com/sidorares/node-mysql2/issues/376

added connect timeout event and tests

---

lib/pool_connection.js
promise.js
test/integration/test-promise-wrappers.js

allow to use object argument in promise api. 

---

.travis.yml
lib/compile_binary_parser.js
lib/compile_text_parser.js
test/integration/connection/test-change-user-plugin-auth.js
test/integration/connection/test-change-user.js
test/integration/connection/test-select-json.js
test/integration/test-pool-disconnect.js

always use utf8 encoding to parse json data type columns

---

lib/connection.js

As discussed in
https://github.com/sidorares/node-mysql2/issues/414#issuecomment-249584274
https://github.com/sidorares/node-mysql2/issues/414#issuecomment-250388825

dont destroy stream, only clear timeout

---

package.json

Update package sqlstring to accept numbers and other value types in `escapeId`.
see PR https://github.com/mysqljs/sqlstring/pull/5

Update package sqlstring

---

examples/promise-co-await/co.js

Fixed co example

---

.travis.yml
appveyor.yml

run lint when LINT=1 in CI

---

lib/parsers/string.js

Probably Fixes https://github.com/sidorares/node-mysql2/issues/458

Removing parser cache

---

promise.js

because this is a fast lib, it should use a fast promise implimentation

use bluebird instead of es6-promise

---

promise.js
test/common.js
test/integration/test-promise-wrappers.js
test/run.js

(sorry, retrying again. Actually there was no need to fetch changes into my repo, githob automatically gives access to forks by default, forgot about that)
@Myhlamaeus this is your pr #567 pulled from your remote to this repo, trying ti figure out why tests fail randomly

Pr 567 tweaks

---

promise.js
test/integration/test-promise-wrappers.js

This fixes both issues mentioned in #574.

Fixing promisified prepare implementation and promisifying returned statement

---

lib/parsers/string.js

Fix node encodings lookup in string parser

---

.travis.yml
appveyor.yml
package.json

ref https://github.com/ashtuchkin/iconv-lite/issues/154

update dependencies and add node 8 to build matrix

---

examples/ssl/rds-ssl.js

removed unnecessary 'fs' requirement and fixed typo

fixed typo

---

promise.js
test/integration/promise-wrappers/test-promise-wrappers.js

https://github.com/sidorares/node-mysql2/pull/614

fix tests for #614

---

lib/packets/packet.js
test/integration/regressions/test-#617.js

Read ms in Packet.prototype.readDateTimeString

---

promise.js

#631 PromiseConnection use promise implementation passed to PromisePool

---

.eslintrc
documentation/Promise-Wrapper.md

no reason for this to be commented out.

Cleanup ES7 example

---

promise.js

Just realised I left this in previously :man_facepalming:

Remove console log in promise wrapper

---

promise.js
test/integration/promise-wrappers/test-promise-wrappers.js

I think it's self explanatory by the title

PromisePool to always use the specified promises library

---

examples/execute.js

`execute` function ought to be called on the `connection` rather than `mysql`.

Fixes execute example

---

README.md

getConnection is passed an err var, without it conn  is null

Change pool example

---

lib/connection_config.js

Fix missing Promise option in checks for Pool

---

lib/commands/execute.js
lib/commands/query.js
lib/helpers.js
lib/parsers/binary_parser.js
lib/parsers/text_parser.js
package-lock.json
package.json

1) Not sure about the package-lock.json, please advise.
2) Since we are on node v6 I took the liberty to do some change some _surrounding_ code:
Make imports use `const`
Remove `object-assign` polyfill.

chore(*): reduce dependencies

---

README.md

Update documentation about caching

---

.travis.yml
lib/auth_41.js
lib/packets/handshake.js

Fix 4.1 auth on servers not supporting PLUGIN_AUTH

---

.travis.yml
lib/auth_41.js
lib/packets/handshake.js

It now uses only the need bytes, to keep auth token valid
Now parse the server initial handshake packet properly.

enhanced AUTH 14, and fix #1053 ER_ACCESS_DENIED_ERROR issue

---

lib/connection.js

put in fix to clear connectionTimeout

added clearing of "connectionTimeout" in _handleNetworkError

---

Changelog.md

Addition of PR #1075 to change log

changelog entry for #1075

---

lib/auth_plugins/caching_sha2_password.md

package name typo

---

lib/connection.js
promise.js
test/integration/connection/test-query-zero.js

There was an error when passing replace parameter with 0.
0 !== undefined
0 || [] goes to [] not 0
if(0) goes to else

Fix incompatibility when zero parameter (#1129)

---

package-lock.json
package.json

Remove unnecessary package cardinal.

fix unnecessary package

---

lib/parsers/parser_cache.js
test/integration/connection/test-nested-tables-query.js

Add table to parser cache key #1142

---

lib/packets/index.js

Fixes #1016
Bug reproduction: https://github.com/sharkykh/node-mysql2-minimizer-bug

Fix incompatibility with code minimizers

---

lib/auth_plugins/sha256_password.js
lib/commands/auth_switch.js

Implement sha256_password authentication plugin

---

.eslintrc
index.d.ts
package-lock.json
package.json
promise.d.ts

Fixes merge conflicts in #1028.

Initial import of types from types/mysql2

---

package-lock.json
package.json

Hi,
Good to see some progress in the typescript area, thanks 💪 
I'm seeing the following issues in the definitions,
This PR fixex these issues
Note that https://github.com/types/mysql2 does not use https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/mysql, but instead uses https://github.com/types/mysql
So I've changed it to use these typings intead

typescript: fix typings

---

index.d.ts
promise.d.ts

closes https://github.com/sidorares/node-mysql2/issues/1212

typings: add ResultSetHeader

---

README.md
typings/mysql/lib/Connection.d.ts
typings/mysql/lib/protocol/sequences/Query.d.ts

I love love love the `rowsAsArray` query / connection option.
However it took me a while to find it, so hoping this makes it easier for others to find.

Typing and readme docs for rowsAsArray

---

lib/pool_cluster.js

feat(poolCluster): add query method

---

index.js
lib/pool_cluster.js
promise.js

fix #609 
add promise version of poolCluster

feat(poolCluster): add promise version

---

lib/commands/execute.js
lib/commands/query.js
test/common.js
test/integration/connection/test-connect-timeout.js
test/integration/connection/test-query-timeout.js

add query timeout option. 
> https://github.com/mysqljs/mysql#timeouts
fix #185 #1104 #1349 and so on.

feat(query): add timeout option

---

lib/pool_cluster.js
promise.js

add execute method for pool cluster, as @vlasky  required  https://github.com/sidorares/node-mysql2/pull/1363#issuecomment-888039732

feat(poolCluster): add execute method

---

lib/commands/command.js
test/integration/connection/test-query-timeout.js

close https://github.com/sidorares/node-mysql2/issues/1387
clear timeout after error occurs
and add a test

fix(timeout): clear timeout after error occurs

---

lib/commands/query.js
lib/parsers/text_parser.js

Addressing #1432  where it was a regression bug from #1402

Fix 100% CPU problem

---

typings/mysql/lib/protocol/sequences/Query.d.ts

This resolves #1265 . I've seen you are covering this feature in your tests, so I hope it is not a problem exposing it for real in the interface.

add namedPlaceholders option to QueryOptions interface

---

typings/mysql/lib/protocol/sequences/Query.d.ts

This is an addition of a type definition. Implementation changes are not included.

fix(typings): Add the infileStreamFactory option to the type definition

---

typings/mysql/lib/Pool.d.ts

Fix typings

---

typings/mysql/index.d.ts
typings/mysql/lib/Connection.d.ts
typings/mysql/lib/protocol/sequences/Query.d.ts

While switching project from `mysql` to `mysql2` I've found few differences at type declarations.
This PR is fixing them.

Added missing type declarations

---

lib/connection.js

this is not important thing, i found some wrong spell in comment.
thank you :)

chore: fix wrong spell comment in lib/connection.js

---

index.d.ts
typings/mysql/index.d.ts
typings/mysql/lib/Connection.d.ts
typings/mysql/lib/protocol/sequences/Prepare.d.ts

This adds type declarations for Prepare & PrepareStatementInfo and then adds prepare and unprepare to the Connection declarations. Fixed #1564

Add type declarations for Prepare & PrepareStatementInfo

---

promise.js

This is a fix related to #1650

Fix async ping function #1650

---

promise.d.ts

Related: https://github.com/sidorares/node-mysql2/issues/1669

Add TS type for createPool to accept a string

---

lib/auth_plugins/mysql_clear_password.js

[tkchk](https://github.com/tkchk) reported a bug in #1403, I faced the same bug.

To fix connection._authPlugin is not a function in mysql_clear_password

---

.github/workflows/ci-bun.yml
.github/workflows/ci-linux.yml
lib/auth_41.js
lib/auth_plugins/caching_sha2_password.js
lib/auth_plugins/sha256_password.js
lib/connection.js
lib/connection_config.js
test/common.js
test/integration/connection/test-select-1.js

https://github.com/sidorares/node-mysql2/issues/1801
( going to track last 3 items separately )

Bun support

---

typings/mysql/lib/Connection.d.ts

fix(types): add decimalNumbers to createConnection/createPool typings

---

lib/commands/server_handshake.js

Resolves https://github.com/sidorares/node-mysql2/issues/1975

Added missing encoding argument to server-handshake

---

lib/connection.js

this should fix issue #2192.
tested with Promise wrapper and Pools only

fix: sql-template-strings compatibility

---

lib/connection.js

fix: sql-template-strings/values

---

lib/connection.js

This PR addresses the problem reported in #2375 
Fixes #2375 
Relates to breaking changes introduced with #2119
Possible workaround for #2177
Relates to #2172

fix: add condition which allows code in callback to be reachable

---

website/package-lock.json
website/package.json
website/tsconfig.json

Just fixing a CI conflict in the new version (`3.2.4`) of **Prettier**.
---
**Related:**
- #2379 
- [**CI - Website #31**](https://github.com/sidorares/node-mysql2/actions/runs/7555709459/job/20571253710)

ci(website): fix Prettier conflict

---

.eslintrc
package-lock.json
package.json

chore: upgrade eslint-plugin-markdown

---

.github/workflows/ci-linux.yml

**Context:**
- https://github.com/sidorares/node-mysql2/pull/2530#issuecomment-2019471292

ci: drop Node.js 14 and 16 from matrix

---

test/esm/unit/parsers/big-numbers-strings-binary-sanitization.test.mjs
test/esm/unit/parsers/big-numbers-strings-text-sanitization.test.mjs
test/esm/unit/parsers/cache-key-serialization.test.mjs
test/esm/unit/parsers/support-big-numbers-binary-sanitization.test.mjs
test/esm/unit/parsers/support-big-numbers-text-sanitization.test.mjs

Moving parser tests to **ESM** and creating tests to binary parser.

ci: improve parser tests

---

.github/workflows/ci-linux.yml

- Drop **Node.js 21**
- Add **Node.js 22**

ci: add Node.js 22 to matrix

---

website/package-lock.json
website/package.json

Updating **Docusaurus** family together 🦖🦕

chore(website): update dependecies manually

---

website/.purc.json
website/package-lock.json
website/package.json

chore(website): upgrade `packages-update` dependency

---

test/common.test.cjs
test/esm/integration/parsers/json-parse.test.mjs
test/esm/integration/parsers/json-string.test.mjs

ci: add tests to JSON parsers

---

website/i18n/zh-CN/docusaurus-plugin-content-docs/current.json
website/i18n/zh-CN/docusaurus-plugin-content-docs/current/index.mdx

Modifying Chinese documentation in some places is still a matter for English

Modifying Chinese documentation in some places is still a matter for English

---

package-lock.json
package.json
test/esm/unit/check-extensions.test.mjs
website/package-lock.json
website/package.json
website/test/unit/check-extensions.test.ts

Adapting tests for **Poku** `v2.x`.

chore(deps): upgrade `poku`

---

.github/workflows/ci-linux.yml

Adding the latest **Node.js** version to CI 🙋🏻‍♂️

ci: add Node.js v23 to matrix

---

.github/workflows/ci-linux.yml

ci: add Deno v2 to matrix

---

website/package-lock.json
website/package.json

Some dependencies of the **Docusaurus** family need to be updated together (see #3229) 🦖🦕

chore(website): update dependencies manually
