sidorares/node-mysql2

lib/commands/execute.js, lib/commands/query.js, test/integration/connection/test-binary-multiple-results.js
Note: prepared statements don't allow to have multiple statements, however, one statement execution can result in multiple results ( example: call to a stored procedure that contains "select1; select 2;" )
This logic ( http://dev.mysql.com/doc/internals/en/com-query-response.html ) is now implemented only in Command/Query code with Execute command states wired to corresponding Query states
=> multiple results support in prepared statements

appveyor.yml, lib/commands/execute.js, lib/commands/query.js, package.json, test/integration/connection/test-stream.js
https://github.com/felixge/node-mysql#piping-results-with-streams2 was missing in this library for quite some time, thanks @krnlde for pointing out in #165
=> Stream row results

README.md, lib/compile_text_parser.js, lib/packets/packet.js, test/common.js, test/integration/connection/test-insert-bigint-big-number-strings.js
Adds support for the `bigNumberStrings` config option which fixes an incompatibility issue with node-mysql.
Previously, numbers <=2<sup>53</sup> were being returned as numbers for columns of type `BIGINT` even when `bigNumberStrings` was set to `true`. This PR aligns the node-mysql2 API with that of node-mysql so that `BIGINT` column values are always returned as strings when the `supportBigNumbers` and `bigNumberStrings` config options are `true`.
=> Support bigNumberStrings config

lib/connection.js, lib/pool.js
This fixes an incompatibility with **node-mysql** since this is in the documentation [here](https://github.com/felixge/node-mysql#escaping-query-values) and [here](https://github.com/felixge/node-mysql#escaping-query-identifiers).
=> Add .escapeId() to Connection and Pool

lib/pool.js
One liner to fix incompatibility noted in #177.
=> Emit enqueue event if conn is queued (closes #177)

lib/connection.js
On the Debian production environment which I am using some combination of OpenSSL and MySQL updates caused connecting via SSL to become impossible, error yilded was
> Error: 139693901379552:error:14082174:SSL routines:SSL3_CHECK_CERT_AND_ALGORITHM:dh key too small:s3_clnt.c:3331:
I figured out that this is likely related to [this](https://bugzilla.redhat.com/show_bug.cgi?id=1228755).
For us to be able to get connecting to the MySQL database working again on our current production setup we needed to control what SSL cipher was being used. (Especially we wanted a cipher which didn't use the *Diffie Hellman protocol*)
This change makes possible to tell which ciphers to use when connecting with SSL. Not sure if this is something you'd like to have, or is this properly prepared for merging, …
=> Make SSL ciphers configurable

lib/commands/query.js, lib/connection.js, lib/pool.js, test/integration/connection/test-named-paceholders.js
Refactored code to use connection.createQuery from both connection.query and pool.query
Also pool.query now returns query command object, so should be possible to chain events:
```js
pool.query({ sql: 'select 1 + ?', values: [1] }).on('end', function() { console.log('done') });
```
see #216 for example code
need to add pool tests before merging this
=> Allow to use pool.query(opts, cb) similar to conn.query()

lib/connection.js
As I mentioned in #245, non-existent options field `rowsAsHash` was used for key evaluation for statement and fields.
This actually fixes some weird behavior when same prepared statement executed with `rowsAsArray` option variable set to `true` lead to mixed results, when sometime you've got rows as array, and other times – as `BinaryRow` objects, e.g.:
```js
var files = pool.executeAsync({
sql: `SELECT id FROM ... `,
rowsAsArray: true
}, [id]);
```
produces mixed results when executed multiple times using pool of connections (console.log output on query result):
```
row [ [ 22500 ] ]
row [ BinaryRow { id: 1000307 } ]
row [ BinaryRow { id: 1000307 } ]
row [ [ 22500 ] ]
row [ [ 22500 ] ]
row [ [ 1000307 ] ]
row [ [ 1000302 ] ]
row [ [ 1000270 ] ]
row []
row [ BinaryRow { id: 1000274 } ] …
```
=> Use rowsAsArray instead rowsAsHash for statementKey and keyFromFields Evaluation

lib/server.js, test/integration/connection/test-disconnects.js
This change removes the unused connections property. It's a very bad memory leak.
=> Remove array memory leak

lib/packets/column_definition.js, lib/packets/packet.js, lib/packets/text_row.js, test/unit/packets/test-column-definition.js, test/unit/packets/test-text-row.js
Fixes: https://github.com/sidorares/node-mysql2/issues/291
Also packet length was calculated incorrectly because `Packet.lengthCodedNumberLength(str)` was always returning `9`
Added some unit tests and tested this in my own project and it seems to work well.
=> added Packet.lengthCodedStringLength

README.md
Hi @sidorares,
Wanted to share what I am using mysql2 for. Also I just published a [blog post](http://imply.io/post/2016/05/04/programmatic-plyql.html) about it.
Basically for a while now I have been developing [Plywood](http://plywood.imply.io/) which is an OLAP focused query planner. It provides a query layer to make it convenient to write [interactive applications](https://github.com/implydata/pivot/). While Plywood can and will eventually support many backends, currently it supports MySQL, Druid, and native JS.
[PlyQL](http://plywood.imply.io/plyql) is a MySQL compatible(ish) language that gets translated into Plywood. Recently I integrated mysql2 into [plyql](https://github.com/implydata/plyql), a command line tool, that effectively provides a SQL interface to Druid - Druid does not …
=> added server example to readme

test/integration/connection/test-timestamp.js
http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_allow_invalid_dates
=> Use SQL_MODE=ALLOW_INVALID_DATES to test invalid timestamp in MySQL 5.7

.travis.yml
Travis CI is bombing me (and everyone else) with email notifications. I personally prefer to track Travis build status via the travis-ci.org and the badge thats part of the README.md already.
This setting (https://docs.travis-ci.com/user/notifications/#Email-notifications) disables email notifications.
=> Update travis to stop sending email notifications

lib/compile_text_parser.js, test/integration/connection/test-typecast-geometry.js
`Work in Progress + Test Case`
While parsing the Geometry values using the `typeCast` some odd error occurs.
```js
> node ./test/run.js && MYSQL_USE_COMPRESSION=1 node ./test/run.js
[0:00:00 0 0/1 0.0% node test/integration/connection/test-typecast-geometry.js]
evalmachine.<anonymous>:11
geometry: function () { return this.parser.parseGeometryValue(); }
^
TypeError: Cannot read property 'parseGeometryValue' of undefined
at Object.geometry (evalmachine.<anonymous>:11:49)
at Object.connection.query.typeCast (/var/www/node-mysql2/test/integration/connection/test-typecast-geometry.js:9:20)
at new TextRow (evalmachine.<anonymous>:15:25)
at Query.row (/var/www/node-mysql2/lib/commands/query.js:197:13)
at Query.Command.execute (/var/www/node-mysql2/lib/commands/command.js:38:20)
at …
```
=> Failing test for geometry typeCast issue

lib/commands/client_handshake.js, lib/connection.js, test/integration/connection/test-error-events.js, test/integration/connection/test-invalid-credentials.js
This will NOT crash the process
```js
var connection = mysql2.createConnection({ invalid credentials });
connection.on('error', handler);
```
But this will
```js
var connection = mysql2.createConnection({ invalid credentials });
connection.once('error', handler);
```
When error are handled in `once` they still bubble up to process level.
**Fixes**
- Handling errors in either `on` or `once` work now
- No multiple error events if handshake resulted in error
Closes #355
=> Catching errors in once crashes process

lib/compile_binary_parser.js, lib/compile_text_parser.js, lib/connection.js, lib/packets/packet.js, test/integration/connection/test-binary-longlong.js, test/integration/connection/test-insert-bigint.js
-  use supportBigNumbers and bigNumberStrings flags in parser
-  pass supportBigNumbers and bigNumberStrings from `query({sql, ...opts})` and `execute({sql, ...opts})` type of calls
-  use supportBigNumbers and bigNumberStrings as part of parser key
- binary protocol: use long.js to calculate resulting number from two 32 byte valuse
- text protocol: fix in detecting potentially big number. Split parseLong* into functions with and without big number checks, use no check version if type is < long
=> 64 bit long fixes

lib/connection.js
fixes #363
@carlok - would you be able to test this `tlssocket` branch?
=> don't use deprecated tls.createSecurePair if TLSSocket is avaiable

lib/pool.js, test/integration/connection/test-named-paceholders.js
Fix for issue #315 
`this.config` on a pool does not contain the namedPlaceholders option, it now lives inside `this.config.connectionConfig`. Thus, namedPlaceholders was always being set to undefined.
I also removed the argument swapping in Pool.execute. This conversion occurs inside connection.execute and does not need to be performed at the pool level. Doing it there actually breaks passing an options object instead of a query.
=> Fix pool namedplaceholders on execute

lib/commands/client_handshake.js, lib/connection.js, lib/pool.js, lib/pool_connection.js, test/integration/test-pool-connect-error.js
see test
might be a side effect of #356,  CCing @sushantdhiman
during `pool.query` or `pool.getConnection` if connection is created (e.i not reused) this part of code is executed: https://github.com/sidorares/node-mysql2/blob/26748034feef277d56f5d97907c4790591f307ec/lib/pool.js#L46
but for some reason, if there is connect time error (bad password or 'too many connections' error from ClientHandshake command is not returned - "error" is emitted on ClientHandshake and there is no error listener there, thus crashing process 
see also:
commands error handling: https://github.com/sidorares/node-mysql2/blob/26748034feef277d56f5d97907c4790591f307ec/lib/commands/command.js#L29-L33
Initial ClientHandshake command: https://github.com/sidorares/node-mysql2/blob/master/lib/connection.js#L105-L110
I …
=> pool connection time error is not propagated correctly to users and as a result process crashes

lib/commands/execute.js, lib/commands/query.js, lib/compile_binary_parser.js, lib/compile_text_parser.js, lib/connection.js, package.json, test/integration/connection/encoding/test-charset-results.js, test/integration/connection/encoding/test-client-encodings.js, test/integration/connection/test-typecast.js
It looks like text protocol parser cache was not used at all: https://github.com/sidorares/node-mysql2/pull/396#issuecomment-246134184
After fix, few tests failed. The reason was over-optimization in parser: encoding was part of compiled parser and if encoding changed between parser invocation the result was incorrect. This is changed to dynamically use charset from field parameter. Another problem was in re-use parser with typeCast options, first time where it's a function and second time where it's `false`. Now typeCast added to parser cache key, when typeCast values differ new parser is generated
TODO: compare benchmarks before/after caching
=> Save correctly compiled parser for re-use

lib/commands/execute.js, lib/commands/prepare.js, lib/commands/query.js, lib/connection.js, test/integration/connection/test-execute-order.js, test/integration/connection/test-load-infile.js, test/integration/connection/test-named-paceholders.js, test/integration/connection/test-stream-errors.js, test/integration/test-rows-as-array.js
network error handler already closes commands in the queue on network error, hovewer there still seems to be possibility to when code is writing to socket after it was already closed:
- connection closed in the middle of wrtiting command
- there was long running multi packet command such as `LOAD INFILE` packets from client to server
Just listening `error` events on socket is not enough, in the scenarios above error is thrown from event loop and it's not possible to handle it
hopefully fixes #289 #57 and #38
solution: 
- add callback to `socket.write` and treat callback error as network error
- stop listening `LOAD INFILE` stream in case of network error
- guard from adding new commands and writing packets if client is in the closed state
=> Don't write to stream when socket is closed

Contributing.md, lib/compile_binary_parser.js, lib/compile_text_parser.js, test/common.js, test/integration/connection/test-change-user-plugin-auth.js, test/integration/connection/test-change-user.js
After docker introduction change user tests were failing at local. This PR fix that.
Also removed `vm` from parser compiler
**Master**
```js
WIP - not implemented yet | packet_parser.execute() in chunks of length 1..packet_length x 156035 packets: 20000  ±20000
packet_parser.execute() toSpeed() 16113.875 17288.962703394758
= 48700000000 ±52300000000 packets/second
read 43 column definitions (select * from mysql.user) x 10000: 235300000  ±3000000
= 1830000 ±20000 columns/second
read 5 chars strings from 10000 bytes buffer x 10000: 1346800000  ±7900000
= 371300000 ±2200000 chars/second
```
**This**
```js
WIP - not implemented yet | packet_parser.execute() in chunks of length 1..packet_length x 156035 packets: 20000  ±20000
packet_parser.execute() toSpeed() 17340.3125 19309.29190577282
= …
```
=> Test Fixes

lib/commands/execute.js
Related to #174 but for prepared statements
=> fix Query.stream exception on prepared statements

lib/packets/column_definition.js, test/integration/regressions/test-#442.js
Closes #422
When encoding is unknown we try to parse name as `binary`. I have added check which will force name parsing to `utf8` in such case. I don't know if its a proper fix. Test case included
=> Fix and tests for garbled column names

lib/commands/change_user.js, lib/commands/command.js, lib/commands/execute.js, lib/commands/prepare.js, lib/commands/query.js, lib/compressed_protocol.js, lib/connection.js, lib/packets/column_definition.js, test/integration/regressions/test-#433.js
see #433 for more details
Actually I'm starting to think that client encoding should be always used for metadata but it's hard to test - in my tests response fields always have same encoding as client regardless of schema (with exception of 'binary' encoding for non-string fields). Will try to check mysql server source to confirm this
=> fix for #433 - use client encoding for errors and metadata with encoding=='binary'

lib/commands/query.js, lib/connection_config.js, lib/constants/server_status.js, lib/packets/resultset_header.js, test/integration/connection/test-binary-multiple-results.js, test/integration/connection/test-multiple-results.js, test/integration/connection/test-track-state-change.js
see #388
Going to be used to implement #389 
implemented deserealizing of 'session change info' structure in OK packet - https://dev.mysql.com/doc/internals/en/packet-OK_Packet.html#cs-sect-packet-ok-sessioninfo
The structure returns list of updated system variables, name of new database (if changed) and list of GTIDs (not implemented yet)
The API is open for discussion, I suggest consider it internal initially and not document (so that this change might go into patch release)
=> add support of CLIENT_SESSION_TRACK in ok packet

benchmarks/unit/packets/column_definition.js, lib/connection.js, lib/pool.js, package.json
There is good performance increase as per the benchmarks
**With Denque**
```
packet_parser.execute() toSpeed() 17463.53125 24954.22432172604
= 44900000000 ±64200000000 packets/second
read 43 column definitions (select * from mysql.user) x 10000: 342000000  ±15000000
= 1260000 ±60000 columns/second
read 5 chars strings from 10000 bytes buffer x 10000: 1664000000  ±8300000
= 300500000 ±1500000 chars/second
```
**Master**
```
packet_parser.execute() toSpeed() 23182.71875 25260.35895211405
= 33900000000 ±36900000000 packets/second
read 43 column definitions (select * from mysql.user) x 10000: 374600000  ±4300000
= 1150000 ±10000 columns/second
Slower then prev result: 1258983.2138447813 ±columns/second %s
read 5 chars strings from 10000 bytes buffer x 10000: 1989000000  ±44000000
= 251400000 …
```
=> Using Denque

lib/connection.js, promise.js, test/integration/regressions/test-#485.js
Fix #485  (Main discussion)
Closes #475 (Past attempt solving this same issue)
**Changes** 
- Directly pass arguments to `execute`
- Added a test which will fail if execute dont release connection properly.
- Fixed options parser which could have failed for `execute(object, undefined, func)`
=> Fix #485, Connection not released when Pool.Execute called without values

promise.js
`PromiseConnection` was missing some functions `Connection` implements.
Hence it was unable to use the `Promise` wrapped connection like
the "real" connection.
This commit adds implementation for all missing asynchronous functions.
Additionally a whitelist is used to determine, which synchronous
functions are implementd by a facade function, passing the call to
the internally used connection instance.
fixes #495 , see pull request #496
=> fix: PromiseConnection missing interface functions from Connection

lib/packets/handshake_response.js
you may discard if not that important :)
=> `packet.skip(23);` means 23 unsafe bytes leak over wire

lib/packets/handshake_response.js
Currently the `if` block looks like it's part of the larger `if/else` block above it, but it's a separate declaration. Adding a newline makes it immediately clear that these are separate logical blocks to readers of the code.
=> Clarifying `if` statement formatting

promise.js, test/common.js, test/integration/test-promise-wrappers.js
Fix #468
Introduce a new PromisePool constructor into promise.js. PromisePool
inherits from EventEmitter, and the following events are re-emitted
from the underlying Pool instance to it:
- acquire
- connection
- enqueue
- release
Methods like `on` can't just be bound to the Pool and added to the object as `this` would be
wrong in the callback: e.g. `this.query` wouldn't return a Promise.
=> Make Promise Pool wrapper extend EventEmitter

.travis.yml, lib/parsers/string.js, lib/pool.js, test/common.js, test/integration/connection/encoding/test-non-bmp-chars.js, test/integration/test-pool-release.js, test/run.js
- use safe-buffer in string decoder #585 
- make tests run in node 0.10
- make pool.execute() work without parameters
=> Safe buffer fixes

lib/connection.js, test/integration/connection/test-connect-time-error.js
this fixes a problem when client connection receives error packet as first packet instead of 'start handshake' packet. This can happen, for example, when number of opened connections is at max_connections. This is different from auth error response packet ( which arrives after 'handshake response' )
The problem itself is side effect of [todo: insert link here. pr where query object returned from pool.query gets 'end' event]
thanks @calebeaires for showing error in https://github.com/sidorares/node-mysql2/issues/606#issuecomment-314084053
=> Fix crash when first packet from server is error packet 

promise.js, test/integration/promise-wrappers/test-promise-wrappers.js
fix sidorares/node-mysql2#577
---
I saw that #577 already had a fix in #578, but you seemed to have some concerns about that solution that I think I share, and I'm eager to see a fix for this issue actually land. So here's what I think the fix should be: it's fully lazy, so no event listeners get added to the wrapped object until one is added to the wrapper, and it removes those listeners as early as possible.
=> redo event delegation in promise wrappers to be lazy, self-cleaning

promise.js, test/integration/promise-wrappers/test-promise-wrappers.js
If an error occurs during execution of a promisifed prepared statement, instead of receiving the real error you are presented with:
```
TypeError: Cannot set property 'message' of undefined
at Execute.onResult (/Users/tom/dev/src/github.com/tsholmes/node-mysql2/promise.js:72:24)
at Execute.Command.execute (/Users/tom/dev/src/github.com/tsholmes/node-mysql2/lib/commands/command.js:30:12)
at Connection.handlePacket (/Users/tom/dev/src/github.com/tsholmes/node-mysql2/lib/connection.js:515:28)
at PacketParser.onPacket (/Users/tom/dev/src/github.com/tsholmes/node-mysql2/lib/connection.js:94:16)
at PacketParser.executeStart (/Users/tom/dev/src/github.com/tsholmes/node-mysql2/lib/packet_parser.js:77:14)
at Socket.<anonymous> (/Users/tom/dev/src/github.com/tsholmes/node-mysql2/lib/connection.js:10 …
```
=> Fix handling of errors in promise prepared statement execute

lib/packets/packet.js, test/integration/regressions/test-#629.js, test/unit/packets/test-datetime.js
For example, MySQL binary protocol data in little endian for
2017-08-14 23:55:29.327:
```
hex:    0b      e107   08   0e     17   37  1d   58fd0400
dec:    11      2017   8    14     23   55  29   327000
unit:   bytes   year   mon  day    hour min sec  microseconds
```
=> correctly parse microsecond in datetime type

lib/packets/packet.js, test/integration/connection/test-binary-longlong.js
pulling commits described in #637
=> parseLengthCodedIntString to return null instead of empty string for null columns

.travis.yml, appveyor.yml, lib/compile_text_parser.js, test/integration/connection/test-typecast.js
If first field  is null then it will corrupt next field value to become null as well.
I dont know reason behind this but this only happens with `typeCast`, even when only `next()` is called. I guess somehow depend upon access order to packet buffer.
https://github.com/sequelize/sequelize/issues/8475
=> test(typecast): first null value, corrupts next field

lib/packets/packet.js
I was using [github:mysqljs/mysql](https://github.com/mysqljs/mysql) and I changed to node-mysql2.
We dont have access to sqlMessage with node-mysql2 so I added it :)
**My tests**
With node-mysql2 :
```javascript
var mysql = require('mysql2');
var connection = mysql.createConnection({user: 'xx', password: 'xxx', database: 'xx', host: 'xxx'});
connection.query("SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'MY_ERR';", function (err, rows) {
console.log(JSON.stringify(err));
/*
Before : {"code":"ER_SIGNAL_EXCEPTION","errno":1644,"sqlState":"#45000"}
After : {"code":"ER_SIGNAL_EXCEPTION","errno":1644,"sqlState":"#45000","sqlMessage":"MY_ERR"}
*/
});
```
With mysql from [github:mysqljs/mysql](https://github.com/mysqljs/mysql)
```javascript
var mysql = require('mysql');
var connection = …
```
=> Added access to the "sqlMessage" of an error

index.js, lib/pool.js, promise.js, test/unit/test-Pool.js
Escape methods already exist on `Pool`, so are only new to `PromisePool`.
(The pre-commit hook went to town prettifying the code.)
Fixes #663.
=> Expose escape & format methods on connection pool

Changelog.md, lib/packets/packet.js, package.json
Changed ```sqlState``` of an error to a string of 5 chars as mysql specifies it [here]
(https://dev.mysql.com/doc/refman/5.5/en/mysql-sqlstate.html) and to  align with [mysqljs/mysql](https://github.com/mysqljs/mysql).
I updated the Changelog and did a minor version bump as asked in #665 
I did not find any tests related to ```sqlState```
Test : 
```js
var mysql = require('mysql2');
var connection = mysql.createConnection({user: 'xx', password: 'xx', database: 'xx', host: 'xx'});
connection.query("SIGNAL SQLSTATE '02000' SET MESSAGE_TEXT = 'My message', MYSQL_ERRNO = '1999';", function (err, rows) {
console.log(JSON.stringify(err));
});
```
Before : 
```json
{"errno":1999,"sqlState":"#02000","sqlMessage":"My message"}
```
After : 
```json
{"errno":1999,"sqlState":"02000","sqlMessage":"My …
```
=> sqlState normalized (error object) && minor version bump && Changelog update

index.js, promise.js, test/integration/promise-wrappers/test-promise-wrappers.js
Make promise pool connection calls to `destroy` proxy pool connection `destroy` method, rather than non-pool connection `destroy` method.
(The prettify commit hook has reformatted a lot of unchanged code once again!)
Relates to #672
=> Remove destroyed promise pool connections from pool

.travis.yml, lib/packets/execute.js, test/integration/connection/test-execute-bind-boolean.js, test/integration/connection/test-execute-bind-date.js, test/integration/connection/test-execute-bind-json.js, test/integration/connection/test-execute-bind-null.js, test/integration/connection/test-execute-bind-number.js, test/integration/connection/test-execute-bind-undefined.js
This PR is a follow on from https://github.com/sidorares/node-mysql2/pull/353 - it sets the type for bind parameters based on the source parameter type.
- Numbers are typed as `DOUBLE`
- JSON is typed as `JSON`
- Booleans are typed as `TINY`
- Dates are converted to string
There's a PR for sequelize that relies on these changes: https://github.com/sequelize/sequelize/pull/8861
=> Use source parameter types

lib/pool.js
Use the built in splice method to avoid reordering the queue and improve performance.
Originally was removed due to https://github.com/sidorares/node-mysql2/issues/226 - but that was when it used 'double-ended-queue', and we now use denque, which does include a splice method.
=> Improve performance of removing connections from pools

documentation/Prepared-Statements.md, lib/connection.js, lib/packets/execute.js, lib/packets/packet.js, test/integration/connection/test-execute-bind-function.js
This tidies up #705 : 
* Moves date serialization to packet.js
* Uses functions in packet.js instead of creating buffers
* Catches use of undefined params earlier (test updated)
Tests are passing locally
=> feat(execute): Tidy up source param types

lib/commands/execute.js
This is to provide more context to error messages when a parameter is undefined.
=> Wrap executePacket.toPacket(1) call with try/catch

index.js, lib/commands/execute.js, lib/commands/query.js, lib/connection.js, lib/parsers/binary_parser.js, lib/parsers/parser_cache.js, lib/parsers/text_parser.js
See #722 for details
When a connection is closed, any compiled parser created for that will
be lost, as the connection is removed.
However, Node/V8 Internals appear to be holding onto any created function.
This can result in memory leaking based on connection cycling and new
parsers being created again.
This change creates a global cache store since everything around the generated
code is not connection specific.
This also completes a TODO to use an LRU cache, although I set a high value
as to avoid running into the leak if the LRU is too small.
An API is provided for anyone who does need to control the max value, as
well as an API to clear the parser cache.
=> Store Compiled Packet Parsers in a global cache - Resolves #722

lib/packets/packet.js
The `noAssert` argument is no longer supported by Node.js and all
input will be validated even if it is passed through. This removes
the argument therefore.
Refs: https://github.com/nodejs/node/pull/18395
Off-topic: the git hooks in use seem to interfere a lot with the contributors will.
It is for example not possible to commit something with `git commit -p` because even if you only apply a few patches, all code is going to be commited anyway. That is not very user friendly :-/
=> fix(packet): remove `noAssert`

lib/connection.js
=> Do not throw an error when a connection ends with a RST,ACK packet

README.md
No code changes, only README changes.
I provided a quick guide on how to use connection pools, as it's currently not documented at all and (although it's quite simple) you have to read the source code to understand how to use it.
=> Added connection pool documentation

lib/packets/handshake_response.js
The `handshake_response.js` `toPacket` function had two typos.
=> Fixes typo in handshake_response.js

lib/pool.js
At the moment mysql2 does not emit any events when a connection is acquired or released back into the pool, which is something mysql-node does support. Adding these helps instrument database usage patterns more comprehensively,  allowing users to better understand how their applications make use of the library, whether they're leaking connections or just using more than they need and help them diagnose connection limit errors and suchlike.
=> Emit pool connection acquire and release events

README.md, lib/connection.js, lib/pool.js, lib/pool_connection.js, package-lock.json, promise.js, test/unit/test-Pool.js
This adds a .promise() function to Pool, Connection, and PoolConnection, which allows you to wrap an existing non-promise instance of any of these objects with a promise wrapper.
See issue https://github.com/sidorares/node-mysql2/issues/809
Code is not well tested yet. I wrote a unit test for Pool which passes but not sure how to test a Connection.
=> Added a .promise() function to Pool, Connection, PoolConnection

lib/commands/query.js, promise.js, test/integration/connection/test-then-on-query.js
This PR includes 3 changes:
- A fix for PromiseConnection.ping(), as it was not failing on errors
- An error is now thrown if .then() or .catch() is called on a non-promise Query
- promise.js was updated to consistently use const instead of var
=> Fix .ping(), error checking for Query.then(), const correctness

lib/connection_config.js, test/common.js, test/integration/connection/test-connect-with-uri.js, test/unit/test-Pool.js
Frequently, I find myself using the following code:
```js
mysql.createPool(process.env.MYSQL_URI);
```
Unfortunately, when passing in a URI from an environment variable, it means that my application is unable to override any of the URI parameters, as createPool and createConnection only accept either URI String or Object parameters, not both at once.
This PR allows you to use both formats, by passing a uri: key into the options:
```js
mysql.createPool({
uri: process.env.MYSQL_URI,
multipleStatements: true
});
```
In the case of overlapping parameters, the Object parameters are currently given preference over the URI String parameters. I'm not sure if that is the correct preference.
=> Added a uri: parameter to the connection config

Changelog.md, package.json
As per title and following issue https://github.com/sidorares/node-mysql2/issues/820.
Regarding the version number:
The new features in this release are backward compatible, therefore I bumped the minor only (following semver).
Given we're also dropping support for node 4, we may want to bump the major.
=> Added changelog for next release

README.md
pool.query() method need requires a string first parameter, optional array as second, and callback (and execute() also)
examples/pool-test.js has to be fixed as well (TODO)
=> document query() method with at least a string

lib/commands/query.js
The 'end' event (emitted by `stream.push(null)`) should always be emitted before the close event.
This fixes issue https://github.com/sidorares/node-mysql2/issues/711
=> Fix issue #711: close emitted before end

lib/connection.js
The "Socket ended by other party error" seems to be caused by the `end` event not being fired in certain cases (TLS connections?). Using the `close` event instead makes sure that timed out connections are removed from the pool.
Related node issue(?): https://github.com/nodejs/node/issues/10871
Fixes #447
=> Use stream close event instead of end

lib/connection.js
Fixes #881
I kinda want to add a test but maybe it would be a good idea to run one of the test instances with `DEBUG=1` instead, that would instantly ensure that they at least don't cause errors :)
In any case it's 3am and I really don't want to deep dive into this right now.
=> fix(debug): remove usage of callee

lib/connection_config.js, test/unit/connection/test-connection_config.js
Sequelizejs passes ssl configuration as a boolean.
This will assign `true` to this.ssl at line 99
```js
this.ssl =
typeof options.ssl === 'string'
? ConnectionConfig.getSSLProfile(options.ssl)
: options.ssl || false;
```
and eventually pass the check at line 115 and assign a property to a boolean that will throw a TypeError in strict mode.
This doesn't attempt to fix the bug, but it gives a better error message.
=> Fixed a bug when ssl config is a boolean and a property is added to it

lib/connection.js
This option allows Node v12.1.0 to connect to a server using 'TLSv1.1' because Node v12.1.0 minVersion default is 'TLSv1.2'.
Otherwise Node v12.1.0 has to be run with --tls-min-v1.1 CLI option.
=> Allow to set minVersion ssl option

lib/commands/query.js
The error event on a connection is never removed with stream local infile, resulting in a MaxListenersExceededWarning from node at the 11th attempt to stream on this connection. This change fixes this problem.
=> Fix a MaxListenersExceededWarning with stream local infile

lib/packets/packet.js
The method `readTimeString` returns a string in all other cases, so it should return `00:00:00`
Fixes: #967
=> Fix #967 - Return a string for '00:00:00' time

lib/commands/index.js, lib/packets/index.js
Fixes https://github.com/sidorares/node-mysql2/issues/890
I tried to create some automated tests for this in the package itself, but that was too hard without bringing in a bunch of dependencies that don't belong in here. So, I just tested it by creating a minimal application that imports my fork of node-mysql2, establishes a connection to a local MySQL instance, and queries a table.
This may not work with all minification libraries or bundlers, but it works with webpack and a minimal babel config that just uses the env preset.
=> Make node-mysql2 compatible with minification

promise.js, test/integration/promise-wrappers/test-promise-wrappers.js
These properties are documented in `mysqljs/mysql` [[`config`](https://github.com/mysqljs/mysql#custom-format)] [[`threadId`](https://github.com/mysqljs/mysql#getting-the-connection-id)] and typed in [`types/mysql2`](https://github.com/types/mysql2/blob/master/promise.d.ts#L8) but not directly exposed in `PromiseConnection`.
=> Add threadId and config getters to PromiseConnection

documentation/Readme.md, lib/commands/execute.js, lib/connection_config.js, lib/packets/execute.js, lib/packets/packet.js, lib/parsers/binary_parser.js, lib/parsers/parser_cache.js, lib/parsers/text_parser.js, test/common.js, test/integration/connection/test-custom-date-parameter.js, test/integration/connection/test-date-parameter.js, test/integration/connection/test-datetime.js, test/integration/regressions/test-#629.js, test/run.js, test/unit/packets/test-datetime.js
Support for the `timezone` connection option as specified by `mysqljs/mysql`:
> `timezone`: The timezone configured on the MySQL server. This is used to type cast server date/time values to JavaScript `Date` object and vice versa. This can be `'local'`, `'Z'`, or an offset in the form `+HH:MM` or `-HH:MM`. (Default: `'local'`)
Inspired by https://github.com/sidorares/node-mysql2/pull/732 but with tests and against current master. Removes the need to run tests with `process.env.TZ = 'UTC'`. It doesn't set the session `time_zone` variable, but the user should do that if the server time zone is not the same as the requested time zone. However, since `time_zone` only applies to `timestamp` columns and date functions &mdash; and not stored `datetime` values &mdash; the client and server really …
=> Add support for timezone connection option

lib/constants/session_track.js, lib/packets/resultset_header.js, test/unit/packets/test-ok-sessiontrack.js
While all known session info types have string following session type int apparently there are cases when rest of the data after type is something different. Simple fix is to only try to read content of known types
ref #989
=> Fix crashing when session info packet does not start with length-coded string

lib/constants/ssl_profiles.js
AWS Aurora Serverless instances use a different root certificate as noted here: 
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless.html#aurora-serverless.tls,
specifically: https://www.amazontrust.com/repository/AmazonRootCA1.pem
=> Update SSL Profile for AWS Serverless Aurora

lib/commands/server_handshake.js, lib/packets/packet.js
there were no other calls to `packet.readString(len, encoding)` that forgot to pass a `len` parameter.
We didn't discuss my change to `packet.readString()` that detects this error and automagically fixes it. I'll remove it if you dislike.
=> [#1029] fix/prevent calls to "packet.readString()" w/ wrong signature

lib/connection_config.js, test/unit/connection/test-connection_config.js
[mysqljs/mysql supports a string or an array for flags](https://github.com/mysqljs/mysql/blob/master/lib/ConnectionConfig.js#L146)
and the TypeScript bindings expect an array (until [this upstream fix](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37722) can be integrated)
=> Support ConnectionConfig.flags as an array

lib/connection_config.js
Hi!
Using `authPlugins` as an option in `createConnection` does not seem to work.
In `connection_config.js`, you get a warning as it is not in the `validOptions` object and is also not assigned to the class further down in the constructor.
In this PR, this is fixed so that `auth_switch.js` can correctly utilize the plugin as it would otherwise not be able to because `connection.config.authPlugins[pluginName]` would be undefined.
I am not sure how `authPlugins` and the new API is supposed to work, but using this code at least works. Please tell me if it is supposed to used in another way.
=> Add missing authPlugins assignment in ConnectionConfig

lib/connection_config.js, lib/pool_config.js
Instead, treat NaN (as well as undefined) as an absent option and use
the default value.
Fixes #721 where a connectionLimit of NaN would render the pool silently
unable to acquire connections.
=> Avoid setting numeric config options to NaN

lib/connection.js, lib/connection_config.js
This PR allows the user to enable keep-alive on the underlying socket with a configurable `initialDelay` parameter, in milliseconds.  Keep-alive is disabled by default.  Example usage:
```js
const pool = mysql.createPool({
host: 'db',
user: process.env.MYSQL_USER,
password: process.env.MYSQL_PASSWORD,
database: process.env.MYSQL_DATABASE,
connectionLimit: 2,
waitForConnections: true,
queueLimit: 0,
keepAliveInitialDelay: 10000, // 0 by default.
enableKeepAlive: true, // false by default.
});
=> Keep alive

lib/connection.js, test/integration/connection/test-connect-after-connection-error.js, test/integration/connection/test-connect-after-connection.js
I wasn't able to find a way to test _fatalError - it wasn't set when either destroying or closing the server connection, however _protocolError was set, so I was at least able to test this.
I suspect there will still be some cases where an error occurs by neither _fatalError or _protocolError are set. In this case `connection.connect` will pass a closed / invalid connection to the callback and any attempt to use this should result in an error, which I think is still acceptable.
=> Fix Connection.connect callback may never be executed (#1136)

lib/pool.js
If a synchronous exception is thrown (primarily by `execute()`), then the connection must be released.  I also made the same changes in #938
=> Release connection on exception

package.json
Adding ES module support to resolve #1093
=> Add ES Module Support

lib/commands/query.js, lib/packets/index.js, lib/pool.js, lib/pool_cluster.js, promise.js
here is a small fix for some industry sandbox env that doesn't have object "global" / "global.process".
=> fix for scope of sandbox without "global" and "global.process"

lib/packets/resultset_header.js
Conditionally importing does not seem to be required (constants only).
When running tests in parallel with Jest and a mysql2 connection we receive warnings as below
```
ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.
at new ResultSetHeader (node_modules/mysql2/lib/packets/resultset_header.js:39:32)
at Query.resultsetHeader (node_modules/mysql2/lib/commands/query.js:102:16)
at Query.execute (node_modules/mysql2/lib/commands/command.js:39:22)
at Connection.handlePacket (node_modules/mysql2/lib/connection.js:417:32)
at PacketParser.onPacket (node_modules/mysql2/lib/connection.js:75:12)
```
If the require statement is moved to the top of the file as per this commit the issue is resolved.
=> Move require to top level of the module

package.json
When importing mysql2 on newer version of node, an error occurs:
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in node_modules/mysql2/package.json
at applyExports (internal/modules/cjs/loader.js:487:9)
at resolveExports (internal/modules/cjs/loader.js:503:23)
at Function.Module._findPath (internal/modules/cjs/loader.js:631:31)
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:949:27)
at Function.Module._load (internal/modules/cjs/loader.js:838:27)
at Module.require (internal/modules/cjs/loader.js:1022:19)
at require (internal/modules/cjs/helpers.js:72:18)
{
code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```
This appears to be caused by this PR
https://github.com/sidorares/node-mysql2/pull/1100
Adding ".": "./index.js" to the exports appears to resolve …
=> Fixed import issue with ES modules

lib/helpers.js, lib/parsers/binary_parser.js, lib/parsers/text_parser.js, test/integration/connection/test-datetime.js
This aligns the `dateStrings` option with mysqljs, allowing to set `dateStrings: ['DATE']` to return
the DATE type as string, but keeping other datetime types processed to Date.
Related: #99
=> feat: allow using `dateStrings` with specific types

lib/pool_cluster.js
This fixes an issue when you close a connection using replication, the `end()` method on pool do not resolve the promise coz of missing callback.
=> Pass in the callback when ending the pool connection.

promise.js
Filter out callback functions that went wrong as input argument in  methods of PromiseConnection and PromisePool.
When **query** & **execute** methods in PromiseConnection & PromisePool get **callback function** as the second argument(which is invalid), it is filtered so that **callback function** cannot be passed to query & execute  method in **connection** & **pool**
=> Fix promise methods

lib/commands/query.js, test/unit/commands/test-query.js
Data type parsers could throw an exception, e.g. `JSON.parse` for the JSON type. Currently, this exception is unhandled and crashes the application that receives it.
This change does the catching and passes it to either the callback, or the error event subscribers in order to support graceful recover if needed.
=> (fix/query): Row parsing could lead to uncaught errors

index.d.ts
My builds started failing today with error 
> TS2339: Property 'authPlugins' does not exist on type 'ConnectionOptions'. 
I've copied the `authPlugins` type declaration from @types/mysql2
=> Add the authPlugins types to ConnectionOptions

package.json
Prior to 2.2.0, an ES6 import of the promise wrapper had to specify a file
extension ("import mysql from 'mysql2/promise.js';"), which made #1100 a
breaking change as only the extensionless version was included in the exports;
this restores promise.js as a valid import.
=> Add 'promise.js' to exports

index.d.ts
- mysql_clear_password in authPlugins currently only supports
Promise<string> type. However AWS.RDS.Signer.getAuthToken returns string, which
causes type error "Type 'string' is not assignable"
getAuthToken Type
Error message:
- This fix will add support for string type as well
=> mysql_clear_password can have string type

documentation/Extras.md, lib/connection.js, test/integration/connection/test-named-placeholders.js
In a project using this package we are trying to transition into using named placeholders. We would like to do this gradually, as some parts of the code cannot be easily transitioned. This change allows the use of unnamed placeholders even when the flag is enabled.
=> Allow unnamed placeholders even if the namedPlaceholders flag is enabled

lib/commands/command.js, promise.js, test/integration/connection/test-errors.js
Fixes #1068 
- Adds an `Error.prototype.sql` property on `command` errors, obtained from `this.sql` (`query.js` and `execute.js`), `this.query` (`prepare.js`) or fallback to `undefined` for all other commands
- Supports errors thrown within the `promise` implementation
- Added tests
- ~Additional code style changes added by pre-commit hook~ (reverted and used `--no-verify` since the changes applied break checks)
=> Expose SQL query in errors

.travis.yml, lib/connection.js, lib/constants/errors.js, lib/packets/index.js, lib/packets/packet.js, test/integration/connection/test-binary-multiple-results.js, test/integration/connection/test-disconnects.js, test/integration/connection/test-execute-nocolumndef.js, test/integration/connection/test-invalid-date-result.js, test/integration/connection/test-multiple-results.js, test/integration/connection/test-protocol-errors.js, test/integration/connection/test-quit.js, test/integration/connection/test-stream-errors.js, test/integration/test-server-close.js
The latest MySQL server versions (up to 8.0.25) introduced some changes that are causing some tests to fail. These changes are mostly related to the following:
- new unexpected packets being sent from the server
- deprecated column metadata details for certain data types such as integers
- stricter SQL rules enforced on date and time values
Additional details about each issue being address are depicted in the corresponding commit message.
Although the changes are mostly constrained to the test suite, there is also a small change in the implementation in order to accommodate the introduction of an additional MySQL protocol packet sent by the server when the connection is closed because of inactivity.
In order to make the test suite more flexible and able to execute in different host and CI …
=> Fix tests to work with the latest MySQL server versions

lib/commands/client_handshake.js, lib/connection.js, test/integration/test-auth-switch-plugin-error.js, test/integration/test-handshake-unknown-packet-error.js
Unknown handshake errors such as ones caused by unexpected packets sent by the server and errors reported by client-side authentication plugins are now considered fatal (similar to what already happens for errors reported by the server during the authentication stage).
Additionally, any kind of fatal error reported during the handshake stage will result in the connection being closed.
Closes #1263.
=> Add proper handshake fatal error handling

test/common.js, test/unit/pool-cluster/test-connection-error-remove.js, test/unit/pool-cluster/test-connection-order.js, test/unit/pool-cluster/test-connection-restore.js, test/unit/pool-cluster/test-connection-rr.js, test/unit/pool-cluster/test-query.js
add unit tests for `poolCluster`.
And I found that `node-mysql2` not support `restoreNodeTimeout` now, I will make a PR later.
=> test(poolCluster): add unit tests

typings/mysql/lib/PoolCluster.d.ts
`createPoolCluster` method takes `BasePoolCluster.PoolClusterOptions` [type](https://github.com/sidorares/node-mysql2/blob/07a429d9765dcbb24af4264654e973847236e0de/typings/mysql/lib/PoolCluster.d.ts#L8) as argument to create a [pool cluster](https://github.com/mysqljs/mysql#poolcluster-options).
When adding nodes to the PoolCluster using the `add` method this parameter type is not correct since we need to pass options to define where nodes are and how to authenticate against them (`host`, `port`, etc.). 
These options are defined in the `PoolOptions` [type](https://github.com/sidorares/node-mysql2/blob/master/typings/mysql/lib/Pool.d.ts#L10) which extends the `Connection.ConnectionOptions` class.
=> Hotfix: incorrect argument type in PoolCluster add method

lib/connection.js, test/integration/connection/test-connection-reset-while-closing.js
Hello 👋 ,
I was having a problem similar to #766 while moving our MySQL database from AWS to Azure.  I would get a successful response AND an `ECONNRESET` error when querying the Azure database.
The fix for #766 didn't seem to be working for me. After digging in a bit, I saw that the error I was getting had a number for the `errno`  property and not the `ECONNRESET` string:
```
Error: read ECONNRESET
at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
at TLSWrap.callbackTrampoline (internal/async_hooks.js:131:14) {
errno: -54,
code: 'ECONNRESET',
syscall: 'read',
fatal: true
}
```
It looks like the `errno` property changed in [node v13](https://nodejs.org/docs/latest-v13.x/api/errors.html#errors_error_errno)
> The error.errno property is a negative number which corresponds to …
=> Update how the ECONNRESET error is caught when connection already closing

promise.d.ts, typings/mysql/lib/PoolConnection.d.ts
A `PoolConnection` object exposes a `connection` property, but that is missing from the typing.
This is the same as a PR I merged on the types/mysql2 project earlier in the year:
https://github.com/types/mysql2/pull/40
=> Add missing `connection` property from the `PoolConnection` type

documentation/Authentication-Switch.md, lib/commands/change_user.js, lib/commands/client_handshake.js, lib/connection.js, lib/connection_config.js, lib/constants/client.js, lib/packets/auth_next_factor.js, lib/packets/index.js, test/integration/connection/test-change-user-multi-factor.js, test/integration/test-auth-switch-multi-factor.js, typings/mysql/lib/Connection.d.ts
MySQL 8.0.27 introduced support for multi-factor authentication, as described in the following link:
https://dev.mysql.com/doc/refman/8.0/en/multifactor-authentication.html
User accounts can now be configured with up to three authentication plugins and corresponding passwords or additional options. Although not all authentication plugins can be used for the 2nd and 3rd factor, any MySQL client should be flexible enough to accommodate those that can.
This proposal follows the same convention used by the official MySQL CLI and introduces three new optional connection options for users to provide passwords for the corresponding _nth_ authentication factor, namely:
- `password1` (symbolic replacement for `password`)
- `password2`
- `password3`
The client handshake workflow was extended to …
=> Add support for multi-factor authentication

typings/mysql/lib/Connection.d.ts
I need to configure minVersion option, there is currently no option for this, I can only configure it via `as SslOptions as any` in  typescript, it's bad. so I created it.
=> Add minVersion for ssl option.

lib/connection_config.js
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
=> refactor: replace deprecated String.prototype.substr()

README.md
I found an issue with the Simplified Chinese documentation hyperlinks on Github Pages. It was originally a hyperlink, but was parsed into a table. It is caused by `|`, so i removed it.
=> Fix Simplified Chinese document button parsing error in Github Pages

typings/mysql/lib/Connection.d.ts
These options are passed directly to `tls.createSecureContext`,
which supports `Buffer` and `Buffer[]` as argument types.
This makes the 'Connecting over encrypted connection' example
compile with TypeScript (since it uses a Buffer from 'fs.readFileSync')
=> Accept Buffer and Buffer[] in typings for key, cert, and ca

lib/helpers.js
I made a [comment here on a fix](https://github.com/sidorares/node-mysql2/issues/846#issuecomment-1172958633) for the cardinal optional dependency issue with Webpack.  I decided to go ahead with the PR as I won't have the configuration set up for too long on my end.
This fixes the issue for at least Webpack, I haven't checked with other bundlers.
I've added a video below to show how my project running Next12/Webpack5 would show the warning, and how after the fix the warning would be gone.  On the right is the node-mysql2 project, and the top left console is my project which has it npm linked so I can test changes.
https://user-images.githubusercontent.com/5728044/177018917-d3ff624a-37c8-4651-8de8-61316c762098.mov
=> fix: webpack projects no longer show warning for cardinal dependency

index.d.ts
When using typescript and/or ESM it's nice to be able to:
```js
import { createServer } from 'mysql2';
```
This PR hoists the `createServer` module.
Let me know if this is way is unacceptable and I can possibly define this within `typings/mysql/...`
=> Ability to use `createServer` in typescript

documentation/Prepared-Statements.md, promise.d.ts
1. The prepared statement typings are missing
2. The documentation of prepare() usage are kinda wrong
Let's say that we have following code (assume we've fixed the typings):
```typescript
async function updateStuffs(updates: [string, string][]) {
const statement = await conn.prepare('UPDATE Users SET A = ? WHERE B = ?');
for (const update of updates) {
await statement.execute(update);
}
statement.close(); // <-- Notice this line
}
await updateStuffs(...);
await updateStuffs(...); // Call multiple times
```
The first call to `updateStuffs` works fine, but later calls (assume the connection didn't get closed) produces the following error:
```
Error: Unknown prepared statement handler (#XXX) given to mysql_stmt_precheck
```
I've searched a bit and found this issue: …
=> fix(typing & documentation): prepared statements usage

index.d.ts, package-lock.json, package.json, tests.json, tsconfig.json, typings/mysql/index.d.ts, typings/mysql/lib/Server.d.ts, typings/mysql/lib/protocol/sequences/Prepare.d.ts, typings/test/server.ts
- Conformed to the way typings are being added currently in the project
- Fixed an issue importing `PrepareStatementInfo` (while we're at it)
=> More complete way of adding typings for the `Server` module

.eslintrc, index.d.ts, lib/commands/prepare.js, lib/commands/server_handshake.js, lib/packets/execute.js, package.json, promise.d.ts, tests.json, typings/mysql/index.d.ts, typings/mysql/lib/Connection.d.ts, typings/mysql/lib/Pool.d.ts, typings/mysql/lib/protocol/packets/index.d.ts, typings/mysql/lib/protocol/packets/params/ErrorPacketParams.d.ts, typings/mysql/lib/protocol/packets/params/OkPacketParams.d.ts, typings/test/connection.ts, typings/test/pool.ts
This PR invalidates #1584 (based on whether or not this PR can be merged). It adds the missing typings and aims to simplify things a bit.
It also takes care of added tests for the common types, fixes a packet issue related to `prepare`, and adds additional listeners for both `prepare` and `execute` when using the module as a MySQL proxy.
These changes are necessary in order to build a more complete (batteries included) MySQL proxy (in typescript) with support for prepared statements (using mysql2 module as a client along with other common clients).
=> Types, tests, and commands Oh my! 🌪️ 

lib/auth_plugins/mysql_clear_password.js, lib/commands/auth_switch.js
This seems like it comes up fairly frequently here (and has come up [on my repo too](https://github.com/beekeeper-studio/beekeeper-studio/issues/832), so figured I'd add this as a core supported plugin.
Not sure if you want to do this or not, but figured I'd open a PR just to see. Seems like a simple fix.
Let me know!
=> Add mysql_clear_password auth plugin

lib/commands/quit.js, test/unit/commands/test-quit.js
Resolves #1638 to the extent that it invokes callback, although the mysql2 error message is "Can't add new command when connection is in closed state" instead of the more specific mysqljs/mysql error message "Cannot enqueue Quit after invoking quit.".
=> renamed done to onResult

.github/workflows/release.yml
refs https://github.com/sidorares/node-mysql2/issues/1631
- this workflow integrates Google's `release-please-action`, which seems like the best option for using release-please and GHA
- if a release was created, it'll also automatically publish to npm
---
@sidorares There is a [lot of configuration](https://github.com/google-github-actions/release-please-action#configuration) available for the Action. Might be worth giving that list a check before merging to ensure it is set up how you would like
=> ci: added workflow to integrate release-please

README.md
I was caught by a quite subtle bug after upgrading from node-mysql to mysql2:
I was retrieving some `sum` values from the DB and then sorting by that field in JS code. because of the way I was processing the data after the sort, the sums were automatically converted from string to number. however, the sort itself was being done on the raw values.
In most of my tests the sum values were all 4 digits long so the output was identical when using mysql and mysql2. It was only when I happened to have a test where some of them where 3 digits long and some were 4 that the bug became apparent (999 would be sorted before 1000 when using mysql but "999" would be sorted after "1000" when using mysql2.
for this reason I think it warrants a warning on the main documentation page where it says it's …
=> highlighted known incompatibility with node-mysql

.github/workflows/ci-linux.yml, .github/workflows/ci-windows.yml
Investigating issue in https://github.com/sidorares/node-mysql2/issues/1668 ( also node 18 been around for more than 6 months now and in LTS )
=> Add node 18 to the build matrix

typings/mysql/lib/Connection.d.ts
Hi, I updated to 3.0.0-rc.1, now the definition of execute parameter has become required, which is wrong.
=> Fix wrong execute method definition.

lib/parsers/text_parser.js, test/unit/parsers/test-text-parser.js
=> fix: typeCast string() parameters for JSON

lib/connection.js, typings/mysql/lib/Connection.d.ts
Right now the hostname presented on a TLS certificate is never validated. This means that man-in-the-middle attacks are trivial when using for example public CAs to sign certificates.
The issue is that anyone can have a public CA sign a certificate for a hostname they own, which is key to the security model there. But with the current functionality in the `mysql2` driver, the hostname is never verified.
This means an attacker could do a man in the middle attack and only has to present a signed certificate but doesn't have to match the hostname.
It does not only apply to public CAs in system roots, but also for example Amazon RDS where a single root chain is also used.
The changes here add an option to explicitly verify the identity on the certificate. This option is available in other …
=> Add identify verification option for TLS

lib/connection.js
I ran into the problems described in https://github.com/knex/knex/pull/2175 recently and I saw that the proposed solution in this issue (expose _fatalError as part of the public api of connection -> use getter in knex) was never implemented. Here's a stab at exposing that property as a getter, and I'll follow up with a PR for knex if this is accepted.
=> Add getter function for connection private property _fatalError

index.d.ts, index.js, lib/auth_plugins/index.js, typings/mysql/index.d.ts
The example of using `authPlugins` given in https://github.com/sidorares/node-mysql2/blob/master/lib/auth_plugins/caching_sha2_password.md is not possible, as this module does not expose a top level `authPlugin` object. This PR adds that top-level object, as well as fully typing for the existing plugins.
=> Expose authPlugins to enable example from docs

lib/connection.js, test/integration/test-pool-end.js
The PoolConnection is listening for the end event to be emitted to close the connection, but the connection is not listening to the underlying end event emitted by the net.Socket.
fixes #1664
=> fix(connection): ensure pooled connections get released

lib/connection.js
This fixes the massive slowness I experienced on some machines (Amazon Linux 2 on AWS EC2), where each query was taking ~60ms. Running a script that executes 100 UPDATE queries in sequence takes ~6.5s before patch, and 0.3s after patch.
And somewhat less interestingly.. the setting doesn't make much difference if I execute the script on my local PC. I'm guessing there are settings at the OS level that can amplify this slowness.
I don't know much about the TCP_NODELAY flag, only that it should always be set for time sensitive network communications (like for a MySQL client). And forgetting to set this flag seems to be a common issue, for example this blog post has a nice explanation: https://vorner.github.io/2020/11/06/40-ms-bug.html
=> Enable TCP_NODELAY flag

package.json
PR makes it so the `typings/test` directory is not included in the built package that goes to NPM. Right now, they do, and contributes 3 files at ~2.7kb to the final output. See https://unpkg.com/browse/mysql2@3.0.0-rc.1/typings/test/ for example of it.
=> Do not include typings/test in built package

typings/mysql/lib/Connection.d.ts
Closes #1765
Thought about linking to a newer ECMAScript spec, but this part of the spec hasn't really change to my knowledge so fine I think to link to an old one.
In case want to use the latest, the link would be https://262.ecma-international.org/13.0/#sec-ecmascript-language-types-number-type.
=> Update link to JS number object specification

lib/connection.js
To fix issue #1334
From MySQL 8.0.24, an [error packet with code 4031](https://dev.mysql.com/doc/mysql-errors/8.0/en/server-error-reference.html#error_er_client_interaction_timeout) is sent to client before connection is closed. This packet has sequenceId == 0, thus the connection will issue a warning "packets out of order", which is not correct.
The changes here is just move the block checking & increasing sequence id to go after check for protocol error, since in case of error, we close the connection and return right away.
=> Fix issue #1334: warning "packets out of order" when handling ER_CLIENT_INTERACTION_TIMEOUT

lib/commands/change_user.js
refs https://github.com/isaacs/node-lru-cache/blob/main/CHANGELOG.md#v7---2022-02
- the `.reset` method became `.clear` in `lru-cache` v7 but the old method was maintained for backward compatibility and given a deprecation warning
- without this change, changing user in `node-mysql2` gives the
following warning: `(node:27579) [LRU_CACHE_METHOD_reset] DeprecationWarning: The reset method is deprecated. Please use cache.clear() instead.`
=> Updated `lru-cache` reset method to clear

lib/connection_config.js, lib/packets/handshake_response.js, test/integration/test-auth-switch.js
MySQL connectors have some [Available Connection Attributes](https://dev.mysql.com/doc/refman/8.0/en/performance-schema-connection-attribute-tables.html).
I add the following built-in connection attributes to Node-MySQL-2.
```
{
'_client_name': 'Node-MySQL-2',
'_client_version': version
}
```
These attributes will help users distinguish which driver the connection comes from.
=> Add default connection attributes

lib/connection.js, typings/mysql/lib/Connection.d.ts
As discussed here: https://github.com/sidorares/node-mysql2/issues/1870
=> feat: maxVersion ssl option to tls.createSecureContext

index.d.ts
As I mentioned in [#1722](https://github.com/sidorares/node-mysql2/issues/1722#issuecomment-1500928005) issue:
Once the [`PoolConnection.d.ts`](https://github.com/sidorares/node-mysql2/blob/master/typings/mysql/lib/PoolConnection.d.ts#L4) has already declared extending the `Connection` interface:
```ts
declare class PoolConnection extends Connection {
connection: Connection;
release(): void;
}
```
Then it doesn't needs to re extend the `Connection` in [`index.d.ts` `#86`](https://github.com/sidorares/node-mysql2/blob/master/index.d.ts#L86) like:
```ts
export interface PoolConnection extends mysql.PoolConnection, Connection {
promise(promiseImpl?: PromiseConstructor): PromisePoolConnection;
}
```
> Causing the error:
> ```
> [...] Interface 'PoolConnection' cannot simultaneously extend …
```
=> fix: PoolConnection redundancy when extending Connection interface in TypeScript

typings/test/connection.ts
When I ran `npm run type-test`, I got a few error messages.  One of the messages was:
> Cannot find module 'mysql2' or its corresponding type declarations.
This PR fixes that error.
<details>
<summary>There are a few more typescript errors, but I don't know the right way to fix those.</summary>
```sh
npm run type-test
> mysql2@3.0.1 type-test
> node ./node_modules/typescript/bin/tsc -p tests.json && mocha typings/test --timeout 10000
index.d.ts:86:18 - error TS2320: Interface 'PoolConnection' cannot simultaneously extend types 'PoolConnection' and 'Connection'.
Named property 'execute' of types 'PoolConnection' and 'Connection' are not identical.
86 export interface PoolConnection extends mysql.PoolConnection, Connection {
~~~~~~~~~~~~~~
index.d.ts:86:18 - error TS2320: Interface …
```
=> Fix a TypeScript test

index.d.ts, typings/mysql/index.d.ts, typings/mysql/lib/Connection.d.ts
@sidorares, this fix is about the `.promise()` option in issue #1936.
I see that in `3.2.1` release you merged the `PR` #1949, but in this `PR` the `Connection` is changed "globally", however in `mysql/promise` types it's causing 3 conflicts because it don't needs the `promise` option, so I rollbacked it before this fix.
<hr />
1. Removed all the `PR` #1949 changes (sorry @bluefeet).
2. Removed all the `promise` options from "global" `Connection` Interface
3. Imported and added the `promise` option only in `mysql` ([typings/mysql/index.d.ts](https://github.com/sidorares/node-mysql2/blob/master/typings/mysql/index.d.ts))
- I don't created a new `promise` method, I just imported the original from:
```ts
import { Pool as PromisePool } from '../../promise';
```
<hr />
- ✅ In `mysql/promise` …
=> fix: ConnectionOptions conflict between mysql and mysql/promise

.github/workflows/ci-tsc-build.yml, package.json, test/tsc-build/index.ts, test/tsc-build/tsconfig.json
1. In `package.json`, add the script `test:tsc-build`, allowing local testing before committing new `PRs`:
- ```sh
npm run test:tsc-build
```
2. In `.github/workflows/ci-tsc-build.yml`, runs the command `npm run test:tsc-build` when new `PRs` are submitted
- ✅ Successfully, it will exit with **`code 0`**
- ❌ In case the `tsc` build command fails, it will print the build errors and exit with **`code 1`**
- I reproduced the pattern from `.github/workflows/ci-linux.yml`
- I didn't understand the `main` branch instead `master`, but I kept by default like all the other `CI` patterns 🥷🏻
3. In `test/tsc-build/index.ts`, only imports the `mysql`, `mysql/promise` and export them
- It allows this CI to not need to be updated because of any future changes within them
4. In …
=> ci: Adding TypeScript build test

lib/connection.js, lib/parsers/parser_cache.js
@sidorares, this time, the fix is in **JavaScript** 🤹🏻‍♀️
<hr />
- #1885
The problem is a compatibility issue between CommonJS and ECMAScript Modules when importing the `lru-cache`.
<hr />
To fix it, I changed the import from `LRU` in `./lib/parser_cache.js` and `./lib/connection.js`:
- from
```js
const LRU = require('lru-cache');
```
- to
```js
const LRU = require('lru-cache').default;
```
Now, it's compatible with both **CJS** and **ESM**.
<hr />
I tested this fix in a latest **NextJS** project and it works perfectly without use the experimental: `serverComponentsExternalPackages: ["mysql2"]`.
- It may be necessary to delete the `./.next` cache folder before the first `npm run` `build` | `dev`.
<hr />
- As I didn't tested in older versions of **Node.js**, the CI tests from this PR will …
=> fix: LRU constructor

README.md, documentation_zh-cn/README.md, lib/connection.js, lib/connection_config.js, typings/mysql/lib/Pool.d.ts
This should make sure that the `enableKeepAlive` option is actually taken into account so that it's possible to disable keepalive. This is related to #1081 and #1586.
Before this change keepalive was always enabled, so I opted to let `enableKeepAlive` default to `true`. If enabled by default is not what we should do I'm happy to change it again.
=> Respect enableKeepAlive option

package.json
Hello, 
Proposal to keep mysql2 compatible to many external APIs, that need the package.json. My usage is for example esbuild plugins, that allow instrumentation through datadog APM.
```
✘ [ERROR] Package subpath './package.json' is not defined by "exports" in /Users/**/node_modules/mysql2/package.json [plugin datadog-esbuild]
node_modules/dd-trace/packages/datadog-esbuild/index.js:45:40:
45 │       const pathToPackageJson = require.resolve(`${packageName}/package.json`, { paths: [ args.resolveDir ] })
```
Don't hesitate to reach out for any complementary information
=> fix: add package.json to exports

.github/workflows/ci-linux.yml, .github/workflows/ci-windows.yml, .gitignore
=> ci: add node 20.x to the build matrix

README.md, documentation/pt-br/README.md, documentation/zh-cn/README.md
Pleased to translate the first part of the documentation into Portuguese (BR) 🎉
This **PR** contains the `README.md` in **portuguese (BR)**.
<hr />
In the translation process, some changes that affect all `README` (`en`, `zh-cn` and `pt-br`):
- I removed every `` comment.
- Updated this line to "**MySQL2**":
- https://github.com/sidorares/node-mysql2/blob/f930f6e0453f6ffb62f46dec40825f0bff2307a1/README.md#L91
- I have added punctuation to all sentences in the text:
- `en`: `:`, `.`
- `zh-cn`: `：`, `。`
- I have patterned the examples a bit by:
- Including `;` in example variables that were missing it
- Adding backticks to tables and columns that were missing it in query strings
- Noticed some simple errors and corrected them (like `isesue`, `everytime`, etc.).
- Added the `Array Results` …
=> documentation: create pt-br README.md

index.d.ts, promise.d.ts, promise.js, test/integration/promise-wrappers/test-promise-wrappers.js, test/tsc-build/mysql/createPool/callbacks/connection.ts, test/tsc-build/mysql/createPool/callbacks/getConnection.ts, test/tsc-build/mysql/createPool/callbacks/release.ts, test/tsc-build/mysql/createPool/callbacks/releaseConnection.ts, test/tsc-build/mysql/createPool/promise/connection.ts, test/tsc-build/mysql/createPool/promise/getConnection.ts, test/tsc-build/mysql/createPool/promise/release.ts, test/tsc-build/mysql/createPool/promise/releaseConnection.ts, test/tsc-build/promise/createPool/connection.ts, test/tsc-build/promise/createPool/getConnection.ts, test/tsc-build/promise/createPool/release.ts, test/tsc-build/promise/createPool/releaseConnection.ts, typings/mysql/lib/Pool.d.ts
This fixes the #1761 and #1563.
<hr />
The [promise.js](https://github.com/sidorares/node-mysql2/blob/f930f6e0453f6ffb62f46dec40825f0bff2307a1/promise.js) didn't have the method `releaseConnection`.
Instead of creating from scratch, I just "extended" it from the `release` method:
```js
releaseConnection(connection) {
if (connection instanceof PromisePoolConnection) connection.release();
}
```
Then, I added the test to [test/integration/promise-wrappers/test-promise-wrappers.js](https://github.com/sidorares/node-mysql2/compare/master...wellwelwel:node-mysql2:release-connection#diff-5b7f569fa112eba31069c6d57e2a1958dd38979a02880434a4f0b02057dac748).
<hr />
I had to fix a few wrong types before to fix the `releaseConnection`.
Before this **PR**, according by typings, this should be possible: …
=> fix: releaseConnection types and promise

test/tsc-build/mysql/createPool/promise/promise.ts, typings/mysql/lib/Pool.d.ts
Fixes the issue #2059.
<hr />
Before this **PR**, the `.promise()` typing tests started from `.promise()['any_tested_method']`, but the `.promise()` itself was not tested.
- This test was based on the the code from https://github.com/sidorares/node-mysql2/issues/2059#issuecomment-1587924922 by @matvejs16.
=> fix: createPool promise as PromisePool

lib/connection.js
TCP keepalive interval time will only take effect if setKeepAlive() is called after the socket object is created.
=> fix: keepAliveInitialDelay not taking effect

typings/mysql/lib/Pool.d.ts
`acquireTimeout` exists only on this one place in repo and when I tried to use it, it was only complaining with deprecation warning that such parameter does not exist and in future versions it will be an error.
As it's not being used anywhere else in the actual code I think it can be safely removed from the TS types as well.
=> fix:  typings

.eslintrc, test/tsc-build/helpers.ts, test/tsc-build/strict-checks/ProcedureCallPacket.ts, test/tsc-build/strict-checks/execute.ts, test/tsc-build/strict-checks/query.ts, test/tsc-build/tsconfig.json, typings/mysql/lib/protocol/packets/ProcedurePacket.d.ts, typings/mysql/lib/protocol/packets/index.d.ts, typings/mysql/lib/protocol/sequences/ExecutableBase.d.ts, typings/mysql/lib/protocol/sequences/QueryableBase.d.ts, typings/mysql/lib/protocol/sequences/promise/ExecutableBase.d.ts, typings/mysql/lib/protocol/sequences/promise/QueryableBase.d.ts
This **PR** looks to fix the Issue #1934.
---
<details>
<summary>
<b>Debugging Process</b>
</summary>
`[ ...RowDataPacket, ResultSetHeader ]`
`[ ...[ ...RowDataPacket ], ResultSetHeader ]`
`ResultSetHeader`
`ResultSetHeader`
`ResultSetHeader`
`ResultSetHeader`
`[ [], ResultSetHeader ]`
`[ [], ResultSetHeader ]`
`ResultSetHeader`
`[ ...[ ...RowDataPacket ], ...[ ...RowDataPacket ], ResultSetHeader ]` 
`ResultSetHeader`
`[ ...[ ...RowDataPacket ], ResultSetHeader ]`
`[ ...[ ...RowDataPacket ], ...[ ...RowDataPacket ], ResultSetHeader ]` 
</details>
---
- Always when a **SELECT** is executed (by itself, multiple queries, with or without results and including together with **INSERT**, **UPDATE**, etc.), the result will be an array with the returned rows (or `rowsAsArray`) and the last item …
=> fix: create ProcedureCallPacket typings

lib/packets/column_definition.js, test/builtin-runner/integration/connection/test-column-inspect.mjs, test/integration/connection/test-binary-multiple-results.js, test/integration/connection/test-execute-nocolumndef.js, test/integration/connection/test-multiple-results.js, test/unit/packets/test-column-definition.js
`ColumnDefinition` object for the sake of performance does not store a lot of human readable data: instead of strings it's a buffer and start/end offset, column type is represented as id, flags are compressed into 32 bit int bitfield etc
Here is current result of `console.log(columns[0])`:
```
ColumnDefinition {
_buf: <Buffer 01 00 00 01 08 33 00 00 02 03 64 65 66 05 6d 79 73 71 6c 05 74 61 73 6b 73 05 74 61 73 6b 73 07 74 61 73 6b 5f 69 64 07 74 61 73 6b 5f 69 64 0c 3f 00 ... 431 more bytes>,
_clientEncoding: 'utf8',
_catalogLength: 3,
_catalogStart: 234,
_schemaLength: 5,
_schemaStart: 238,
_tableLength: 5,
_tableStart: 244,
_orgTableLength: 5,
_orgTableStart: 250,
_orgNameLength: 6,
_orgNameStart: 263,
characterSet: 63,
encoding: 'binary',
name: 'status',
columnLength: 4,
columnType: …
```
=> feat: improved inspection of columns

.github/workflows/ci-bun.yml, .github/workflows/ci-osx.yml, lib/connection.js, test/builtin-runner/regressions/2052.test.mjs, test/common.js, test/integration/connection/test-disconnects.js, test/integration/connection/test-protocol-errors.js, test/integration/connection/test-quit.js, test/integration/connection/test-select-ssl.js, test/integration/connection/test-stream-errors.js, test/integration/connection/test-then-on-query.js, test/integration/regressions/test-#82.js
- raw stream 'data' events were not disconnected before starting TLS socket ( looks like node disconnects them for us, bun does not )
- use `TLS.connect()` instead of `new TLS.Socket()` + `secureSocket._start()`
- move logic from 'secure' handler to a `TLS.connect(options, callback)` callback. Note: if handled via event, correct document name should be `"secureConnection"` - see https://nodejs.org/dist/latest-v20.x/docs/api/tls.html#event-secureconnection
- fixes in `verifyIdentity` logic
Note: requires bun >= 0.6.13 due to functionality added in https://github.com/oven-sh/bun/pull/3457
=> fix: make startTls code compatible with Bun

typings/mysql/lib/protocol/packets/OkPacket.d.ts, typings/mysql/lib/protocol/packets/ResultSetHeader.d.ts
Just showing how this appears for final user:
---
---
=> chore: deprecate `OkPacket` type and `changedRows` property

promise.d.ts, promise.js, test/builtin-runner/integration/pool-cluster/test-promise-wrapper.mjs, test/integration/promise-wrappers/test-promise-wrappers.js, typings/mysql/lib/PoolCluster.d.ts
Removed events from promise wrapper that aren't fired by pool cluster.
I've seperated this into 2 commits. The first adds a failing test the second fixes that test
=> Update events that are propegated from pool cluster to include remove

documentation/en/Extras.md, lib/connection.js, lib/connection_config.js, typings/mysql/lib/Connection.d.ts
This PR provides support for the `infileStreamFactory` option at the connection level. This will be useful for users who are looking to validate the file path at the connection/pool level. For downstream libraries like [sequelize](https://github.com/sequelize/sequelize) and [typeorm](https://github.com/typeorm/typeorm), exposing this option at the connection-level will also allow users to set `infileStreamFactory` option through the [`dialectOptions`](https://sequelize.org/docs/v6/other-topics/dialect-specific-things/#mysql) and [`extra`](https://typeorm.io/data-source-options#mysql--mariadb-data-source-options) parameters respectively.
With the change, the `infileStreamFactory` option can be supplied when instantiating a new connection:
```js
const fs = require("fs");
const mysql = …
```
=> feat: add conn-level `infileStreamFactory` option

promise.d.ts, typings/mysql/lib/Connection.d.ts, typings/mysql/lib/Pool.d.ts, typings/mysql/lib/PoolCluster.d.ts, typings/mysql/lib/protocol/sequences/Query.d.ts
The listener parameter of `emitter.on` takes a variable list of parameters instead of an array. See https://nodejs.org/api/events.html#passing-arguments-and-this-to-listeners for an example.
=> Fix EventEmitter on method sigatures to use spread syntax

lib/commands/client_handshake.js
this is just a simple PR to fix typo, from
```
connnection
```
to
```
connection
```
=> fix: typo on unsupported SSL connection

typings/mysql/lib/protocol/packets/FieldPacket.d.ts
This ought to fix https://github.com/sidorares/node-mysql2/issues/1276.
I confirm object in v3.6.3.
```
{
catalog: 'def',
schema: 'for_test',
name: 'id',
orgName: 'id',
table: 'hotels',
orgTable: 'hotels',
characterSet: 63,
encoding: 'binary',
columnLength: 10,
type: 3,
flags: [ 'NOT NULL', 'PRIMARY KEY', 'AUTO_INCREMENT' ],
decimals: 0,
typeName: 'LONG'
}
```
=> fix: Malformed FieldPacket

lib/connection_config.js, test/unit/connection/test-connection_config.js
This is PR to make changes as per last discussion here - https://github.com/sidorares/node-mysql2/pull/1621#issuecomment-1236397707
Also resolves https://github.com/sidorares/node-mysql2/issues/1384
Added decodeURIComponent for username, password, host and database. Currently, if mysql DB has password with special characters like '@', it isnt working at all it seems. After this change, this seems to be working. Also the discussion also clarifies that we should go ahead with this minimal change at least to keep it consistent with MySQL docs.
=> fix: add decodeuricomponent to parse uri encoded special characters in host, username, password and datbase keys

.github/workflows/ci-osx.yml
=> ci: improve OSX workflows

website/docs/contributing/website.mdx, website/docs/documentation/00-index.mdx, website/docs/documentation/mysql-server.mdx, website/docs/documentation/typescript-examples.mdx, website/docs/examples/connections/create-connection.mdx, website/docs/examples/connections/create-pool.mdx, website/docs/examples/connections/createPoolCluster.mdx, website/docs/examples/queries/prepared-statements/delete.mdx, website/docs/examples/queries/prepared-statements/index.mdx, website/docs/examples/queries/prepared-statements/insert.mdx, website/docs/examples/queries/prepared-statements/select.mdx, website/docs/examples/queries/prepared-statements/update.mdx, website/docs/examples/queries/simple-queries/delete.mdx, website/docs/examples/queries/simple-queries/index.mdx, website/docs/examples/queries/simple-queries/select.mdx, website/docs/examples/queries/simple-queries/update.mdx, website/docs/faq/how-to-handle-errors.mdx, website/docs/index.mdx, website/docs/stability-badges.mdx, website/i18n/pt-BR/docusaurus-plugin-content-docs/current/index.mdx, website/i18n/zh-CN/docusaurus-plugin-content-docs/current/index.mdx, website/src/pages/index.tsx
@sidorares, _maybe_, finally a simple way to record anything we want into _[Changelog.md](https://github.com/sidorares/node-mysql2/blob/master/Changelog.md)_, for example:
- **fix(docs):** GitHub MDX parser conflict
- **fix(website):** i18n home breadcrumb
This way is not exclusive to **Release Please**, but to **Conventional Commits** itself.
ℹ️ In these cases, it's important to note that merging will create a release.
> I'll use this PR to see it in practice and "announce" the Documentation Website 🧑🏻‍🔧✨
---
I see it in this [commit](https://github.com/nextauthjs/next-auth/commit/1b9ef7f1259bbd367f2e71a809bc5c8489259445) from [next-auth](https://github.com/nextauthjs/next-auth).
Then, it appears as:
> ## Bugfixes
> - **docs:** update links, fix codeblocks, rephrase …
=> feat(docs): release documentation website

test/common.js
Currently, the `tools/wait-up.js` test only recognizes an error when the MySQL Server returns a connection error, but if there is another type of error, it continues the loop infinitely:
https://github.com/sidorares/node-mysql2/blob/2419c4974149ff1d35f9e93476d780a4cce844c9/test/common.js#L35-L38
This _PR_ sets a maximum limit of **5 minutes** if the connection is not established.
> Reviewing this step (CI) on all OS systems, the time takes between 1 second and ~2 minutes, so I've chosen to set the limit at twice the longest time.
=> ci: fix infinite loop on wait-up step

.github/workflows/ci-osx.yml
> See this _PR_ also as a discussion based on ["osx is a low priority and intended to be a smoke test"](https://github.com/sidorares/node-mysql2/pull/2308#issuecomment-1842002931) comment.
It's been some time that **GitHub** has been failing `macOS-based` tests.
These false positives motivated two other _PRs_ (#2308 and #2348), but the problem isn't really with the **CI**.
---
Since the tests "against" the **MySQL Server** already take place in `CI - Linux`, I would like to propose that the test focus on **Node.js** versions for `macOS-based` tests (how it's already done in `CI - Windows`), reducing the chance of false positives.
---
Currently, I frequently try and retry the `CI - OSX` until it passes without false positives.
=> ci: refactor CI - OSX

.github/workflows/ci-bun.yml, test/integration/connection/test-select-1.js, test/integration/connection/test-select-ssl.js
**Bun Canary**'s tests are successfully completed, but the process doesn't terminate. This _PR_ fixes it by implementing an additional test when the connection is closed.
---
**Related:**
- https://github.com/sidorares/node-mysql2/pull/2386#issuecomment-1899067601
- [**CI - Bun #656**](https://github.com/sidorares/node-mysql2/actions/runs/7573924660/attempts/3?pr=2386)
=> ci(bun): fixes the process exit in Bun Canary tests

lib/parsers/string.js
While getting an iconv decoder isn't particularly slow, I noticed it happens a lot when decoding lots of varchar rows. From internal testing, with 5000 rows of a table containing two varchar utf8mb3 columns (length 100 and 500), I'm seeing about 12% speedup with this change.
=> Perf: cache iconv decoder

test/tsc-build/strict-checks/typeCast.ts, typings/mysql/lib/Connection.d.ts, typings/mysql/lib/parsers/typeCast.d.ts, typings/mysql/lib/protocol/sequences/Query.d.ts
This _PR_ adds missing types to the `field` param and changes the `typeCast` typings from `any` to `TypeCast` on query level.
~I'm following the issue #649 before moving on.~
---
Based on #649, I'll keep typeCast as it is on `execute`, but adding the typings comments:
```ts
/**
* ...
* 
* For `execute`, please see: [typeCast not supported with .execute #649](https://github.com/sidorares/node-mysql2/issues/649).
*/
```
=> fix(types): add missing types to TypeCast

test/integration/connection/test-typecast.js
This _PR_ just continues the work of #1784, keeping all its commits.
> I opted to open a new _PR_ to trigger all the new tests added since then and preserve the original _PR_ (#1428).
---
Explaining the changes:
- https://github.com/sidorares/node-mysql2/pull/1784#issuecomment-1907238907
=> ci: add geometry typecast test

lib/parsers/binary_parser.js, test/integration/connection/test-select-1.js, test/integration/connection/test-select-ssl.js, test/integration/connection/test-type-cast-null-fields-execute.js, test/integration/connection/test-type-casting-execute.js, test/integration/connection/test-typecast-execute.js, test/integration/connection/test-typecast-geometry-execute.js, test/integration/connection/test-typecast-overwriting-execute.js, test/integration/connection/test-typecast-overwriting.js, typings/mysql/lib/Connection.d.ts, typings/mysql/lib/protocol/sequences/Query.d.ts
This _PR_ introduces **typeCast** for the `execute` method and allows the use both from **connection level** and **query level**.  
- Usage is strictly and precisely as it is used in the `query` method.  
- The modifications to the binary parser were adapted from the text parser.  
---
Using the benefits of type customization without losing the advantages of the `execute` method.
- #649
- #717
About #1446 (_RFC: deprecate typeCast and introduce resultsMapper_), I believe that as long as typeCast is still used, it's really useful that it works for both methods.
---
> I duplicated and refactored all the derived TypeCast tests for `query` and shaped them to work in `execute`, as well as creating new ones.
For benchmark comparison, see …
=> feat: introduce typeCast for `execute` method

test/tsc-build/strict-checks/typeCast.ts, typings/mysql/lib/parsers/typeCast.d.ts
It seems #2390 forgot to add the optional encoding parameter.
=> fix: support encoding for string type cast

.github/workflows/ci-osx.yml
After several attempts and workarounds, I finally came up with the simple idea of trying to install **MySQL Server** directly on `macOS` instead of **Docker**.
**The results:**
- Now **CI - OSX** tests finish even earlier than **CI - Windows** ones and probably along with **CI - Linux**
- The longest "**Wait mysql server is ready**" step took `90ms` in my tests
- Less than 5 minutes for all existing CI to finish
> Sometimes the solution is simpler than we expect 🧑🏻‍🔧
=> ci: fix OSX timeout due to large steps

lib/commands/query.js, package-lock.json, test/integration/connection/test-stream.js
This pull request addresses a problem I have found with this pull request - [#2389](https://github.com/sidorares/node-mysql2/pull/2389).
When using streams with a pause (introduced by a timeout or similar asynchronous operation), the stream prematurely closes, leading to an `Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close`.
Here's a code snippet to reproduce the issue:
```javascript
const mysql = require('mysql2/promise');
(async () => {
const connection = {
user: '***',
host: '***',
database: '***',
password: '***',
};
const dbConnection = mysql.createPool(connection);
const query = dbConnection.pool.query(`select n from sequential_data limit 5`).stream();
for await (const row of query) {
await new Promise(r => setTimeout(r, 1000));
console.log(row)
}
await dbConnection.end();
})(); …
```
=> Fix premature close of the stream when it is paused

package-lock.json, package.json, test/run.js, test/unit/test-Pool.js, tools/create-db.js, tools/generate-charset-mapping.js
While working on another PR, I noticed a problem with tests that have been occurring for a long time.
Tests are started using `urun`, but when analyzing the logs, there are some inconsistencies:
It counts the total files, but change the step while still running the previous test:
```sh
[0:00:00 0 1/132 0.8% node test/integration/test-auth-switch-plugin-async-error.js]
[0:00:00 0 2/132 1.5% node test/integration/test-auth-switch-plugin-async-error.js]
```
---
Some time counters don't respect a specific rule:
```sh
[0:00:00 0 4/132 3.0% node test/integration/test-auth-switch.js]
[0:00:00 0 4/132 3.0% node test/integration/test-handshake-unknown-packet-error.js]
[0:00:00 0 5/132 3.8% node test/integration/test-handshake-unknown-packet-error.js]
[0:00:00 0 5/132 3.8% node …
```
=> ci: ensure all tests are performed

typings/mysql/lib/parsers/index.d.ts, typings/mysql/lib/parsers/typeCast.d.ts, typings/mysql/lib/protocol/packets/Field.d.ts
This **PR** just expose (export) all TypeCast typings:
- **TypeCast**
- **TypeCastField**
- **TypeCastGeometry**
- **TypeCastNext**
- **TypeCastType**
The `Field` interface has been deprecated, suggesting to use `TypeCastField` instead.
Now, it's possible for **TypeScript** users:
```ts
import mysql, { TypeCast, TypeCastField, TypeCastNext } from 'mysql2/promise';
const typeCast: TypeCast = (_: TypeCastField, next: TypeCastNext) => next();
// ...
await conn.execute({
sql: `SELECT * FROM test`,
typeCast,
});
```
- The same for `mysql` import.
---
It was motivated by this [commit](https://github.com/sequelize/sequelize/blob/34f2413e7984039b0e47d73ae971a6e417eae954/packages/core/src/dialects/mysql/connection-manager.ts#L9) from **Sequelize**, where they needed to import type cast `Field` …
=> fix(types): expose TypeCast types

.gitattributes
This PR simply indicates the **./website** directory as a documentation directory.
=> chore(docs): create .gitattributes

.github/workflows/ci-coverage.yml, .github/workflows/ci-osx.yml
There are some different behaviors as mentioned by @sidorares in https://github.com/sidorares/node-mysql2/pull/2472#issuecomment-1980620283:
- New and old MySQL Server versions
- SSL as `0` and `1`
- Compression as `0` and `1`
As the tests now run equally for all versions of **Node.js** and both platforms (**OS**), there's no need to send a report for each version of them.
That's why I opted to create an individual CI for the coverage report.
Naturally, to compare the coverages with the `master` branch, `CI - Coverage` will now be run for each push on the `master` too.
=> ci: report coverage data to Codecov

README.md, website/docs/index.mdx, website/i18n/pt-BR/docusaurus-plugin-content-docs/current/index.mdx, website/i18n/zh-CN/docusaurus-plugin-content-docs/current/index.mdx
There are two new badges for the **README.md** plus both **en**, **zh-CN** and **pt-BR** website docs:
[![GitHub Workflow Status (with event)][ci-image]][ci-url]
[![Codecov][coverage]][coverage-url]
[coverage]: https://img.shields.io/codecov/c/github/sidorares/node-mysql2
[coverage-url]: https://app.codecov.io/github/sidorares/node-mysql2
[ci-url]: https://github.com/sidorares/node-mysql2/actions/workflows/ci-coverage.yml?query=branch%3Amaster
[ci-image]: https://img.shields.io/github/actions/workflow/status/sidorares/node-mysql2/ci-coverage.yml?event=push&style=flat&label=CI&branch=master
=> docs: add badges for CI and Coverage rate

codecov.yml
@sidorares, if you _want_ to allow the **Codecov** app to this repository, these conditions (configurable) will now be considered **CI** failures:
- ❌ More than **2%** loss of coverage compared to the base
- ❌ Less than **90%** of total coverage
> Actual coverage is **90.25%**.
=> ci: ensure coverage limits

Changelog.md
> From:
---
* **cache:** improve cache key serialization ([#2424](https://github.com/sidorares/node-mysql2/issues/2424)) ([0d54b0c](https://github.com/sidorares/node-mysql2/commit/0d54b0ca6498c823098426038162ef10df02c818))
---
> To:
* **security:** improve cache key formation ([#2424](https://github.com/sidorares/node-mysql2/issues/2424)) ([0d54b0c](https://github.com/sidorares/node-mysql2/commit/0d54b0ca6498c823098426038162ef10df02c818))
* Fixes a potential parser cache poisoning attack vulnerability reported by Vsevolod Kokorin (Slonser) of Solidlab
* update Amazon RDS SSL CA cert ([#2131](https://github.com/sidorares/node-mysql2/pull/2131)) ([d9dccfd](https://github.com/sidorares/node-mysql2/commit/d9dccfd837d701f377574b85a05586be89015460))
=> docs: fix change logs from v3.9.3

website/docs/examples/connections/create-connection.mdx, website/docs/examples/connections/create-pool.mdx, website/docs/examples/connections/createPoolCluster.mdx
Remove **Amazon RDS** related issues from docs (examples) due to #2131.
=> docs: remove RDS related issues

lib/constants/ssl_profiles.js
This fixes the issue described in https://github.com/sidorares/node-mysql2/issues/2541.
There seems to have been a mistake while updating the cert-chain in https://github.com/sidorares/node-mysql2/pull/2131 , which was released in `3.9.3`.
The cert-chain was changed into a single string where before each of the certificates were separate array elements.
=> fix(SSL): separate each certificate into an individual item

.nycrc, Contributing.md, codecov.yml, package.json
This _PR_ improves the **Contributing Guidelines** based in some recent events.
---
1. Force all files to be checked in the coverage test using the `all` option.
- Files that were ignored (**0%**):
- lib/packets/binlog_query_statusvars.js
- lib/results_stream.js
2. Include a manual coverage check:
- When submitting a _PR_ with the base before **Codecov** was implemented, it will not verify coverage.
- Example: [#2518](https://github.com/sidorares/node-mysql2/pull/2518)
- <img width="480" alt="Screenshot 2024-04-02 at 16 07 29" src="https://github.com/sidorares/node-mysql2/assets/46850407/02d812f2-53fe-4bf6-8f24-61435b8ce7d9">
---
1. Add two new sections to **Development**:
> ### Commits and Pull Request Titles
> 
> To ensure a clean commit history pattern, please use the [Conventional …
=> fix(docs): improve the contribution guidelines

lib/parsers/binary_parser.js, lib/parsers/text_parser.js, test/esm/unit/parsers/big-numbers-strings-sanitization.test.mjs, test/esm/unit/parsers/support-big-numbers-sanitization.test.mjs
This _PR_ continues the #2424 work, ensuring the type of parameters received in the connection and query options for both text and binary parsers.
=> fix(security): improve sanitization for big numbers support

.nycrc, lib/parsers/binary_parser.js, lib/parsers/text_parser.js, test/common.test.cjs, test/esm/unit/parsers/prototype-binary-results.test.mjs, test/esm/unit/parsers/prototype-text-results.test.mjs
Finishing the tasks started in #2424 (and #2572).
This _PR_ ensures a clean object evaluation for every item in results.
This is the final evaluation for both text and binary parsers:
```js
const result = Object.create(null);
Object.defineProperty(result, 'constructor', {
value: Object.create(null),
writable: false,
configurable: false,
enumerable: false
});
// ...
// nestTables
if (!result[${tableName}]) result[${tableName}] = Object.create(null);
```
> I also tried a simple `Object.freeze(result)`, but the unit tests (specific to this) didn't pass as expected 🔓
---
These changes preserve security without affecting the end user:
```js
const [results] = await connection.query('SELECT 1+1 AS `test`'); // or execute
results[0].test.toFixed(2); // '2.00' ✅
results[0].addCustomProp = true; // …
```
=> fix(security): improve results object creation

package.json
Currently, `.cjs` and `.mjs` files aren't checked by **ESLint**.
=> ci: ensure test lints

typings/mysql/lib/Auth.d.ts
Just a minor character missing as I assume it was supposed to be `joinServerPublicKey`  instead of `jonServerPublicKey`.
=> Fixed typing for caching_sha2_password where misspelt jonServerPublicKey is replaced by onServerPublicKey

.github/workflows/ci-linux.yml, lib/auth_plugins/caching_sha2_password.js, test/deno.ts
Closes #2686
[Deno uses](https://github.com/denoland/deno/blob/b21004b1d16ad7b67c7b1cd235abf792bf9d9777/ext/node/polyfills/internal/crypto/cipher.ts#L430) default `RSA_PKCS1_PADDING` for publicEncrypt while [in node](https://github.com/nodejs/node/blob/2079a7aec4323e32ed4ae72bc56ac9125c72fe79/lib/internal/crypto/cipher.js#L84) it's `RSA_PKCS1_OAEP_PADDING` by default. As a result `PERFORM_FULL_AUTHENTICATION_PACKET` step returns password encoded differently from what server expects ( note: mysql versions prior to 8.0.5 might expect RSA_PKCS1_PADDING padding, need to validate that and maybe potentially use based on the server? https://github.com/mysql-net/MySqlConnector/issues/489 )
=> fix: support deno + caching_sha2_password FULL_AUTHENTICATION_PACKET flow

lib/helpers.js, lib/parsers/binary_parser.js, lib/parsers/text_parser.js, test/esm/unit/parsers/ensure-safe-binary-fields.test.mjs, test/esm/unit/parsers/ensure-safe-text-fields.test.mjs
Improves the changes from #2591 by validating `nestTables` final fields and tables.
---
I'm not sure about the need to validate when used in combination with the `rowAsArray` option:
> For now, I've applied validation to all the properties created in `result` object.
```js
} else if (options.rowsAsArray) {
lvalue = `result[${helpers.fieldEscape(i.toString(10))}]`;
} else {
```
=> fix(security): sanitize fields and tables when using nestTables

lib/connection_config.js
Resolves https://github.com/sidorares/node-mysql2/issues/2599.
TL;DR: having the `keepAliveInitialDelay` set to 0 by default behaves differently on some environments causing ECONNRESET errors. You're not able to set it to `undefined` again.
=> fix(connection_config): remove keepAliveInitialDelay default value

lib/connection_config.js, lib/parsers/binary_parser.js, lib/parsers/text_parser.js, typings/mysql/lib/Connection.d.ts, website/docs/documentation/00-index.mdx
Added configuration to support jsonStrings.
Check https://github.com/sidorares/node-mysql2/issues/1072 for more details about this feat
=> feat: Add jsonStrings configuration

codecov.yml
This _PR_ doesn't change the previously defined coverage percentages.
**Codecov** initiates two tests (`project` and `patch`). The `patch` analyzes the percentage file by file, without considering the overall project context, which can cause CI failures even when the project coverage is in line with the established.
In order to maintain better productivity, this _PR_ quiets the `patch` CI.
CI examples:
---
Example of _PRs_ that would be less productive even with proper overall coverage:
- #1919
- #2289
- #2757
=> ci(coverage): disable Codecov patch

lib/parsers/parser_cache.js
replace parser cache with a new one on setMaxParserCache to avoid TypeError, because `max` is now read-only on LRU caches and cannot be altered.
=> fix: setMaxParserCache throws TypeError

lib/parsers/binary_parser.js, test/esm/integration/parsers/typecast-field-string.test.mjs
This _PR_ fixes a break changing reported in **Sequelize** (https://github.com/sequelize/sequelize/issues/17141) after introducing `typeCast` for execute method.
Following the same approach of _PR_ #2398, this _PR_ ensures that the `typeCast` usage for both `query` and `execute` methods are strictly equivalent when using `field.string()`.
> This isn't a new feature, but a part that was missed in #2398.
To illustrate it better:
```js
// typeCast: (field) => field.string()
assert.strictEqual(query.date, execute.date, 'DATE');
assert.strictEqual(query.time, execute.time, 'TIME');
assert.strictEqual(query.datetime, execute.datetime, 'DATETIME');
assert.strictEqual(query.timestamp, execute.timestamp, 'TIMESTAMP');
assert.strictEqual(query.tiny.signed, execute.tiny.signed, 'TINY (signed)'); …
```
=> fix(typeCast): ensure the same behavior for `field.string()` with `query` and `execute`

test/common.test.cjs, test/esm/regressions/2052.test.mjs, test/integration/connection/test-execute-type-casting.test.cjs, test/integration/connection/test-type-casting-execute.test.cjs, test/integration/connection/test-type-casting.test.cjs, test/integration/connection/test-typecast-geometry-execute.test.cjs, test/integration/connection/test-typecast-geometry.test.cjs, test/integration/connection/type-casting-tests.test.cjs
Some tests statically check for **MySQL Server** `v8`, where otherwise they understood it as `v5`.
These adjustments ensure that the tests dynamically check for **MySQL Server** versions.
=> ci: adapt tests for MySQL v9

.github/workflows/ci-linux.yml
Currently, **GitHub Actions** uses **Node.js** `v22.5.0`, that brings an error for _CLI_ dependencies (`<command> not found`).
This bug has been fixed in **Node.js** `v22.5.1`, but I'm deactivating it from the matrix for now in order not to block the _CI_ workflows.
- https://github.com/nodejs/node/issues/53902#issuecomment-2240584024
=> ci: temp disable Node.js 22.x from matrix

lib/constants/types.js, typings/mysql/lib/constants/Types.d.ts, typings/mysql/lib/parsers/typeCast.d.ts
This adds the new MySQL 9.0 vector type. It can still be handled like a binary blob for now I think. Maybe it's worth in the future to directly decode / parse it into an array of floats here?
=> Add basic vector type

.github/workflows/ci-mysql.yml, lib/packets/packet.js, lib/parsers/binary_parser.js, lib/parsers/text_parser.js, test/esm/integration/connection/test-vector.test.mjs, test/esm/regressions/2052.test.mjs
this is a continuation of work started in https://github.com/sidorares/node-mysql2/pull/2866
with this change [VECTOR](https://dev.mysql.com/doc/refman/9.0/en/vector.html) values are returned as array of JS numbers
=> feat: return VECTOR values as array of numbers instead of raw Buffer

.github/workflows/ci-linux.yml
This reverts commit 8c8d44f95bdfec4bb876fd60c18bc1e55c33da55.
---
Checking if **GitHub Actions** has updated **Node.js** to post `v22.5.0`.
=> ci: revert "ci: temp disable Node.js 22.x from matrix (#2870)"

promise.js
The implementation of `PromisePoolCluster#getConnection` does not match the capabilities of `PoolCluster#getConnection` nor the definition in `promise.d.ts`.
This change corrects this by adding the missing `pattern` and `selector` parameters which are passed through to the underlying method.
Fixes #1381 
Note: I may have missed them, but I didn't see any tests for PromisePoolCluster to update or add to with this change.
=> Add pattern and selector to PromisePoolCluster#getConnection

.github/workflows/release.yml
Related: https://github.com/sidorares/node-mysql2/issues/2996#issuecomment-2317743360
=> chore(npm): improve transparency by adding provenance

lib/pool.js, test/integration/test-pool-release-idle-connection-replicate.test.cjs, test/integration/test-pool-release-idle-connection-timeout.test.cjs, test/integration/test-pool-release-idle-connection.test.cjs
This PR addresses issue [#3020](https://github.com/sidorares/node-mysql2/issues/3020) by improving the connection cleanup process in the MySQL pool. The changes ensure that both connections exceeding the `config.maxIdle` setting and expired idle connections (those exceeding the `config.idleTimeout`) are correctly cleaned up.
- **lib/pool.js**
- Updated the connection cleanup logic to check for both `config.maxIdle` and expired connections based on `config.idleTimeout`.
- **New tests:**
- Added a new test `test-pool-release-idle-connection-timeout.test.cjs` to verify the removal of idle connections after the timeout period.
- Adjusted `test-pool-release-idle-connection.test.cjs` to reflect the new cleanup behaviour.
- Improved connection cleanup mechanism in `lib/pool.js`.
- Added a new …
=> Updated connection cleanup process to handle expired connections and those exceeding `config.maxIdle`

lib/connection.js, lib/parsers/parser_cache.js, lib/parsers/string.js, package-lock.json, package.json, test/integration/connection/test-execute-cached.test.cjs
Fixes #1885, Fixes #1953, Fixes #1965, Fixes #1970, Fixes #2001, Fixes #2537, Fixes #2619, Fixes #2752.
---
> [!IMPORTANT]
>
> This _PR_ replaces the **lru-cache**.
- Resolves all issues related to "`LRU is not a constructor`" since it is fully compatible with both _CJS_ and _ESM_ environments, from **Node.js** 8 onwards using **zero** _pollyfill_ (it works even in older browsers).
> [#1885](https://github.com/sidorares/node-mysql2/issues/1885), [#1965](https://github.com/sidorares/node-mysql2/issues/1965), [#1970](https://github.com/sidorares/node-mysql2/issues/1970), [#2001](https://github.com/sidorares/node-mysql2/issues/2001), [#2537](https://github.com/sidorares/node-mysql2/issues/2537), [#2619](https://github.com/sidorares/node-mysql2/issues/2619)
- The same solution above also …
=> fix: resolve LRU conflicts, cache loss and premature engine breaking change

.github/workflows/canary.yml
Closes #2996.
A visual example:
- The hash is the same as the short `HEAD` commit that triggered the deploy.
---
Ignored commits patterns:
```sh
[[ "$MESSAGE" =~ build\(deps-dev\) ]] ||
[[ "$MESSAGE" =~ build\(deps\) ]] ||
[[ "$MESSAGE" =~ chore\(master\) ]] ||
[[ "$MESSAGE" =~ chore\(deps\) ]] ||
[[ "$MESSAGE" =~ chore:\ update\ dependencies ]] ||
[[ "$MESSAGE" =~ docs: ]] ||
[[ "$MESSAGE" =~ ci: ]] ||
[[ "$MESSAGE" =~ cd: ]] ||
[[ "$MESSAGE" =~ docs\(.*\): ]] ||
[[ "$MESSAGE" =~ ci\(.*\): ]] ||
[[ "$MESSAGE" =~ cd\(.*\): ]] ||
[[ "$MESSAGE" =~ chore\(website\) ]]
```
They aren't ignored (intentionally):
- No deps `chore`
- Any `refactor`
=> cd: add canary deploy

.github/workflows/ci-linux.yml
Although `TCP.setNoDelay` was implemented in https://github.com/denoland/deno/pull/26263, the latest release on **GitHub Actions** doesn't seem to have included this fix.
To prevent CI blocking, I'm temporarily removing the canary version until the problem is resolved 🙋🏻‍♂️
Related:
- https://github.com/denoland/deno/issues/26177
=> ci: temp remove Deno canary from matrix

lib/packets/packet.js, lib/parsers/binary_parser.js, test/integration/connection/test-datetime.test.cjs
=> fix: datetime fields returned without time part when time is 00:00:00

lib/pool_cluster.js, promise.js, test/esm/integration/pool-cluster/test-promise-wrapper.test.mjs, test/tsc-build/mysql/createPoolCluster/remove.test.ts, test/unit/pool-cluster/test-connection-retry.test.cjs, test/unit/pool-cluster/test-remove-by-name.test.cjs, test/unit/pool-cluster/test-remove-by-pattern.test.cjs, test/unit/pool-cluster/test-restore-events.test.cjs, test/unit/pool-cluster/test-restore.test.cjs, typings/mysql/lib/PoolCluster.d.ts
The pull request enables support for the poolCluster's [restoreNodeTimeout](https://github.com/mysqljs/mysql?tab=readme-ov-file#poolcluster-options) option, which should resolve the issue #2315.
=> feat(PoolCluster): implemented `restoreNodeTimeout`

website/src/css/_history.scss, website/src/css/custom.scss, website/src/css/stability/_main.scss
This _PR_ just remove the noise warnings when working in the website due to deprecated **Sass** resources.
**Related:**
- https://github.com/sass/sass/issues/3513.
=> chore(website): remove deprecated `Sass` resources

.github/workflows/ci-coverage.yml, .github/workflows/ci-linux.yml, .nycrc, lib/commands/execute.js, lib/commands/query.js, lib/connection_config.js, lib/helpers.js, lib/parsers/static_binary_parser.js, lib/parsers/static_text_parser.js, package.json, test/common.test.cjs, test/esm/integration/parsers/json-string.test.mjs, test/integration/connection/test-nested-tables-query.test.cjs, test/integration/connection/test-typecast.test.cjs, test/integration/regressions/test-#433.test.cjs, typings/mysql/lib/Connection.d.ts
I'm hoping to help push for getting the interpreting parser available (this makes it possible to use mysql2 as an alternative to [mysql](https://github.com/mysqljs/mysql) on Cloudflare Workers).
I opened this as a new PR because I have some bandwidth to address further comments in the PR if they come up. This code merely applies the recommended fixes as noted by @shiyuhang0 to the original PR by @sidorares https://github.com/sidorares/node-mysql2/pull/2099 (the original commit history is maintained and the branch was rebased onto master).
This could also be created as a PR to `deoptimise-large-rows` branch, however the maintainers recommend moving forward.
=> feat(`disableEval`): add static parsers

package.json
Just fixing a warning from **npm** when publishing:
```
npm warn publish npm auto-corrected some errors in your package.json when publishing.  Please run "npm pkg fix" to address these errors.
npm warn publish errors corrected:
npm warn publish "repository.url" was normalized to "git+https://github.com/sidorares/node-mysql2.git"
```
- Not related to https://github.com/sidorares/node-mysql2/pull/3377#issuecomment-2635170534.
=> chore: fix repository url for npm package

lib/parsers/static_text_parser.js
The support for `VECTOR` packets (**MySQL 9+**) has not been included with the static text parser in #3365. This _PR_ just fixes it.
=> fix(query): support `VECTOR` packets in static parser

.github/workflows/benchmark.yml, .github/workflows/canary.yml, .github/workflows/ci-coverage.yml, .github/workflows/ci-linux.yml, .github/workflows/ci-mysql.yml, .github/workflows/ci-osx.yml, .github/workflows/ci-tsc-build.yml, .github/workflows/ci-website.yml, .github/workflows/ci-windows.yml, .github/workflows/gh-pages.yml, .github/workflows/lint.yml, .github/workflows/release.yml
This _PR_ reorganizes the tests in a way that allows reusing **MySQL** versions and variations.
Also, **MySQL 9** will also run through the coverage workflow, preventing issues like in #3379 _(and that's how I discovered the related issue)_.
Another point is that we only tested version `8.0.x`, instead of every minor versions.
Now, we test:
- `mysql:5.7`
- `mysql:8.0`
- `mysql:8.1` _(new)_
- `mysql:8.2` _(new)_ 
- `mysql:8.3` _(new)_ 
- ~`mysql:8.4`~ _(soon)_ 
- `mysql:9.0`
- `mysql:9.1` _(new)_ 
- `mysql:9.2` _(previously as `latest`)_
I've also reused it better to avoid repeated tests, reducing from **116** to **100** workflows in total.
Finally, I updated all **Node.js** `20.x` to the latest _LTS_ (`22`).
> [!NOTE]
> - If there's a specific patch version worth adding, we can also add …
=> ci: improve workflows

.github/workflows/benchmark.yml
The old `actions/cache` version is no longer supported.
=> ci(benchmark): upgrade actions/cache to v4

package-lock.json
`c8` is a development dependency to check code coverage and its vulnerability doesn't affect **MySQL2** installation.
Updating it just for good practices.
=> chore(deps): force update for vulnerable development dependencies

.github/workflows/codeql-analysis.yml
**CodeQL Action** `v1` is deprecated. This _PR_ upgrades it to its latest version.
For reference:
- https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/
- https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/
- <img width="480" src="https://github.com/user-attachments/assets/36a6a058-710a-4f0d-9f06-2441608733d9" />
=> ci: upgrade CodeQL Action

website/docs/documentation/connect-on-cloudflare.mdx
try to close #2179
**Summary**
- To fix the error `window is not found`, replace node `Timers` with web timers
- To fix the error `Code generation from strings disallowed for this context`, using the static parser in PR #2099
- To fix the error `crypto.hash() is not a function`, polyfill node `crypto` with`webcrypto`, and modify the functions which directly/indirectly called the `crypto` library as async function.
**TODOs**:
**Usage**
For users, they need to:
1. Add `node_compat = true` flag to polyfill the missing node modules
2. Add `useStaticParser` flag to force mysql2 to use static parser.
For example: https://github.com/Mini256/mysql2-cloudflare-test/blob/1f339a85f4457b696f122503051991326dbc23dc/src/index.ts#L30
=> feat: support Cloudflare Workers

lib/constants/encoding_charset.js, lib/packets/resultset_header.js
`query("SET NAMES utf8;");` command returns instruction from the server "please use utf8mb3 client character set"
2 issues we had:
- we did not have utf8mb3 in the `EncodingToCharset` map
- in case of encoding name is not recognised we set `undefined` to connection config `charsetNumber`, and next command fails
Fixes #3338
=> Fix for SET NAMES utf8 causing an unknown encoding error

lib/commands/query.js, test/integration/connection/test-stream-error-destroy-connection.test.cjs
When a stream errors (due to break, throw, etc.) the connection can remain paused indefinitely.
To reproduce, create table `test` with 500 rows and run the below. The script will never exit.
```ts
import { createPool } from 'mysql2';
const pool = createPool({
database: 'test',
host: '127.0.0.1',
port: 3306,
user: 'user',
});
const results = pool.query('select * from test;').stream();
for await (const result of results) {
break;
}
pool.end();
```
See https://github.com/sidorares/node-mysql2/issues/3596
=> fix: destroy connection when stream errors

lib/commands/query.js, test/integration/connection/test-stream-error-destroy-connection.test.cjs
This _PR_ continues #3769 work and fixes #3596. It also seems to resolve #1847 and resolve #1168, ensuring that `destroy` and error events are properly issued (not using _`try-catch`_, but _`stream.on('error', () => {})`_ approach, which is the expected pattern for callbacks).
---
In #3769, it destroys the connection on error to ensure that the stack is not blocked, but this approach can be aggressive, as a query error shouldn't destroy the connection.
In this _PR_, the approach is to destroy the current stream itself on error and emits the appropriate events, ensuring its functionality and allowing users to catch errors that were not previously emitted, as reported in #1847.
---
The test that checks the events is not reached and the script is silently ended prematurely:
Now all tests are …
=> fix(stream): resume connection when stream errors or is destroyed

typings/mysql/lib/PoolCluster.d.ts
This aligns the TS type of the `PoolCluster.end()` method to match the JS implementation in [pool_cluster.js](https://github.com/sidorares/node-mysql2/blob/6bfad13a4ce98b4534acc7daae340d027db63479/lib/pool_cluster.js#L232-L265).
=> fix(typings): missing callback to PoolCluster.end()
